### ISSUE TITLE
App Launch shortcut for ERTflix

### ISSUE THREAD

**Issue by smith113311** [PRProd/HA-Firemote#108]
### Describe the bug

The App Launch shortcut for ERTflix does not appear to work, although other shortcuts I've tried have. This is probably just a link issue. The correct package source is "t.yi.erthybrid".

### To Reproduce

Same behavior in both my Android media players.

### Expected Behavior

The app should launch.

### Which Type of Device Do You Own?

nVidia Shield 2017
miTV Stick

**Comment by PRProd** [comment]
@smith113311 Thanks for letting me know!

In issue #96 it was determined that [the app name is **t.yi.erthybrid**](https://github.com/PRProd/HA-Firemote/issues/96#issuecomment-1538755405) just as you mention, so that it what was [published in the code](https://github.com/PRProd/HA-Firemote/blob/main/dist/HA-Firemote.js#L496-L503).  I wrote the shortcut, tested it, published it, and the requester [confirmed that the shortcut is working](https://github.com/PRProd/HA-Firemote/issues/96#issuecomment-1539558320) so I think we need to determine what could be different in your situation.

Let's try a few things:
1. Which version of Firemote are you currently using?  [v2.2.1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.2.1) is the latest.  If you are not at 2.2.1 yet, I would recommend you upgrade.
2. After pressing the ERTFLIX button on your Firemote card, do any error messages appear in the developer console?  Developer Tools -> States -> (search for your device by typing its name under filter entities) -> Observe what is written beside the heading **adb_response:**
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/229fb592-4ce0-4ff1-8fd6-4ffc77f4b580)
3. Try a full system restart of your Home Assistant host, as well as the device you are using to access it.

Please let me know the outcome of these steps so I can further assist you.  I'm here to help.

**Comment by smith113311** [comment]
Dug a little deeper and it turned out the culprit was a slightly outdated version of the actual app.

Initially I was getting the following error on nVidia Shield 2017:

adb_response: >-
  Starting: Intent { cmp=t.yi.erthybrid/com.arxnet.soeasytv.MainActivity }

  Error type 3

  Error: Activity class {t.yi.erthybrid/com.arxnet.soeasytv.MainActivity} does
  not exist.

Troubleshooting steps:

1. I tried calling a "Media Player: select source" script which worked as expected.

2. Updated the actual ERTFlix app (I have automatic updates disabled by default) and that resolved the issue. 

...... 👍  ......

**Comment by PRProd** [comment]
Hooray :tada: I'm glad it's working for you now!
