### ISSUE TITLE
New Shaw BlueCurveTV App Launch Button  does not work.

### ISSUE THREAD

**Issue by jsd58** [PRProd/HA-Firemote#136]
### Describe the bug

New Shaw BlueCurveTV App Launch Button  does not work.

Device Family = Amazon Fire
Amazon Fire Device Model = Fire TV (4 Series - 2021)
Remote Style: Default for Fire TV (4 Series - 2021)
Compatibility Mode: Default for Fire TV (4 Series - 2021)
App Launch Button 1:  Shaw BlueCurve TV
App Launch Button 2:  Spotify
App Launch Button 3:  Kodi
App Launch Button 4:  YouTube

All  "App Launcher Buttons" work, with the exception of Shaw BlueCurveTV App Launch Button

Code Editor Text is as follows:

type: custom:firemote-card
entity: media_player.fire_tv_192_168_1_236
device_family: amazon-fire
device_type: fire_tv_4_series
compatibility_mode: default
app_launch_1: shaw-bluecurve-tv
app_launch_2: spotify
app_launch_3: kodi
visible_name_text: Fire TV Remote
defaultRemoteStyle_override: ''
app_launch_4: youtube

When Shaw BlueCurveTV App Launch Button  is selected nothing happens, no error appear in System Log and no entry appears in logbook when Shaw BlueCurveTV App Launch Button  is selected.

### To Reproduce

Add Shaw BlueCurveTV App Launch Button to remote and select the button.

### Expected Behavior

Shaw BlueCurveTV App Launches on Fire TV.

### Which Type of Device Do You Own?

Fire TV Model = AMZ-K24NE5_4K43N400C
Software Version = FIRE OS 7.6.3.3 (PS7633/3449)
Fire TV Home Version = 6450027.1

### Troubleshooting Steps Completed

Checked to see if any other app has issues, no.
Deleted Lovelace Custom: Firemote Card, reinstalled and reconfigured.
Restarted Home Assistant
Powered off Fire TV and restarted.

Non of which helped to resolve issue.

### Additional context

Shaw BlueCurveTV app that is installed on the Fire TV is = Version 7.1.0.004
App Developer = Shaw Communications
Original Release Date = Nov. 24, 2021
Last update = May 9, 2023
Sold by = Amazon.com.ca, Inc.
ASIN = B09K2HDGTY

**Comment by PRProd** [comment]
@jsd58 - Bummer.  I was concerned that might happen when I made this comment in #132
> Because I'm not in Canada, I was unable to download this app through the store, and I had to go about it a different way. I'd like your help to confirm that I have added it correctly. 

Because of those regional limitations, I'll need you to complete the steps under the heading [Details For App Requests](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) that can be found [here](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F) so I can understand what your Amazon Fire device needs.  As soon as you complete that for me, I will get this fixed for you.

**Comment by PRProd** [comment]
@jsd58 ~ Have you had the opportunity to try this yet?

**Comment by jsd58** [comment]
Sent you this via return email. Not sure if you got it.
adb_response: mSurface=Surface(name=org.xbmc.kodi/org.xbmc.kodi.Main)/@0x7e7a70 mCurrentFocus=Window{b6d4204 u0 org.xbmc.kodi/org.xbmc.kodi.Main} mFocusedApp=AppWindowToken{cc68ac2 token=Token{a5e7b0d ActivityRecord{11821a4 u0 org.xbmc.kodi/.Main t689}}} hdmi_input: null device_class: tv entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_X_XXX?token=b03658c232b75e1ae3de2092508a9ef65a24774c21b1b985a4dba50655219115&cache=1686376602.733099friendly_name: Fire TV 192.168.X.XXX supported_features: 22961 source_list: Kodi app_id: org.xbmc.kodi source: Kodi
Attache also attched 
![Screenshot firemote setup](https://github.com/PRProd/HA-Firemote/assets/11403792/567c996d-2602-4882-bd52-c41856f24601)
is a screen shot of the firemote setup

TY jsd58

**Comment by PRProd** [comment]
@jsd58 - My apologies for the late reply, I've been enjoying some time away with my family.

After looking at the response you sent, it appears that you did not have the Shaw BlueCurveTV app open at the time you ran the command, but instead you had the kodi app open.  Could I ask you to go through the [Details For App Requests](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) instructions one more time, ensuring that the correct app is open when you run the command?

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/05929b09-5966-481d-84af-0254316db96b)

**Comment by PRProd** [comment]
@jsd58 ~ Have you had the opportunity to retry this yet?

**Comment by jsd58** [comment]
By "retry this yet" I'm guessing you mean, have I tried to see if the Shaw button works? Latest version I have is v2.3.8 and no it does not yet work.
 But if your asking if I have retried the steps your emailed me 4 days ago? Yes I did and emailed you the new data the same day. In case you did not get this email, below is a copy of the post I send you.

Here is the data you requested, I have "X'd" out part of my ip addy for security precautions.

source_list:
  - ca.shaw.freerangetv.tenfoot
app_id: ca.shaw.freerangetv.tenfoot
source: ca.shaw.freerangetv.tenfoot
adb_response: '/system/bin/sh: abd: not found'
hdmi_input: null
device_class: tv
entity_picture: >-
  /api/media_player_proxy/media_player.fire_tv_192_168_X_XXX?token=6d03984066eb9e8e0e101ea1b973ae1447ca1e30670fc47dd24415913cdec6ba&cache=1687557299.92081
friendly_name: Fire TV 192.168.X.XXX
supported_features: 22961 

Dave

**Comment by PRProd** [comment]
Dave

I'm not sure what's happening when you hit reply on the thread update emails that Github sends you, but they aren't always making it to me.  All I am able to see is the conversation thread on the Github issue page here [https://github.com/PRProd/HA-Firemote/issues/136](https://github.com/PRProd/HA-Firemote/issues/136). 

Judging by that conversation thread, it appears that at least two of the replies you sent never actually made it to me.  Sorry for the frustration, I wish there was something I could do to help ensure that your messages were being received and posted to this thread properly, but that's out of our control.  The only suggestion I can make is that you visit the message thread and reply through the Github page instead of replying directly to the update email.

Unfortunately, I also have some more bad news for you... it appears that the command you tried had a typo, resulting in this failure message: ``adb_response: '/system/bin/sh: abd: not found'``

Please try again, following the [instructions listed here](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) ensuring that you are running this command:
```
adb shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp|mInputMethodTarget|mSurface'
```

Thanks, and sorry again for the frustration of your messages not making it through as expected.

-Doug

**Comment by jsd58** [comment]
Email problems easily solved, I'll just post and look for responses here  :-).
This look more like what ya need?

 Dave

adb_response: mSurface=Surface(name=ca.shaw.freerangetv.tenfoot/com.xfinity.cloudtvr.view.PlayerActivity)/@0xc09522f
  mCurrentFocus=Window{3b757f3 u0 ca.shaw.freerangetv.tenfoot/com.xfinity.cloudtvr.view.PlayerActivity}
  mFocusedApp=AppWindowToken{b38d47b token=Token{bd3640a ActivityRecord{aed4c75 u0 ca.shaw.freerangetv.tenfoot/com.xfinity.cloudtvr.view.PlayerActivity t690}}}
hdmi_input: null
device_class: tv
friendly_name: Fire TV 192.168.X.XXX
supported_features: 22961
source_list: ca.shaw.freerangetv.tenfoot
app_id: ca.shaw.freerangetv.tenfoot
source: ca.shaw.freerangetv.tenfoot
entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_X_XXX?token=5de49cea906321a941a2ac332af3b35f11b02c188070ec461f34e7993e4ab82c&cache=1687894791.314348

**Comment by PRProd** [comment]
That looks like what I need!  Thanks!  I'll keep you updated.

**Comment by jsd58** [comment]
Shaw has recently merged or been taken over by Rogers and in doing so have decided to re brand the "Shaw Bluecurve TV" app, the app will now be called "Ignite TV (Shaw". https://www.shawdirect.ca/english/support/article/8329/ and the google play app link is https://play.google.com/store/apps/details?id=ca.shaw.freerangetv.
I ran the the instructions you sent again for the new app and got this:

adb_response: mSurface=Surface(name=ca.shaw.freerangetv.tenfoot/com.xfinity.cloudtvr.view.PlayerActivity)/@0xc68e5fc
  mCurrentFocus=Window{6bf6a17 u0 ca.shaw.freerangetv.tenfoot/com.xfinity.cloudtvr.view.PlayerActivity}
  mFocusedApp=AppWindowToken{e692479 token=Token{9df1d40 ActivityRecord{497f0c3 u0 ca.shaw.freerangetv.tenfoot/com.xfinity.cloudtvr.view.PlayerActivity t756}}}
hdmi_input: null
device_class: tv
friendly_name: Fire TV 192.168.X.XXX
supported_features: 22961
source: com.amazon.tv.launcher
entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_X_XXX?token=5c4afc3458e85c2674d01fb8e35cee0800abf28b0f9de064bb4e5e4cfc892fcc&cache=1688278156.379878

Hope this helps
jsd (Dave)

**Comment by PRProd** [comment]
Apologies for the delay.  I've had some work and some health issues that have kept me tied up lately.  Don't worry!  I haven't forgotten about you!  :smiley:

**Comment by PRProd** [comment]
Could you please download the newest "pre-release" version [v2.3.9-b1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.3.9-b1) and check to see if the new Ignite TV app launch button works?

**Comment by jsd58** [comment]
Bingo, works like a charm. Ty for your efforts.

Dave (jsd58)

**Comment by jsd58** [comment]
When time permits, is there a possibility for adding a "TSN" launcher. In fact there are several Canada only apps that do no show on the launcher list, perfectly understandable. If you would like I can compile a list for you. No rush from my point a view but thought it may help for future needs.

Dave

**Comment by PRProd** [comment]
@jsd58 - Since there are literally 100s of thousands of apps out in the wild, it would be impossible (and impractical) for me to try to just add everything I can find.  As it turns out, most of the app shortcuts on the Firemote card are apps that I don't or can't use in my region.  It's not a "no thanks, Canada" sort of thing.  :wink: :canada:

When there are specific apps shortcuts that you want, just open a new issue like you did with this one, and I will work on getting them added.  I prefer a SEPARATE issue for each app request because that really helps me with keeping things organized.

Since this one is finally ready to go, I'll close this issue for now.  I look forward to hearing from you again soon!

**Comment by jsd58** [comment]
Understood and will do. Thank you for all that you have accomplished, its a great addon, a definite thumbs up.

**Comment by PRProd** [comment]
Thanks!  Don't forget to hit the "star" button on this project!  

Fun fact: when you star this project, I have a Home Assistant automation that plays a happy song to encourage me.
