### ISSUE TITLE
[New App Shortcut]: Zattoo

### ISSUE THREAD

**Issue by Icecoke7** [PRProd/HA-Firemote#14]
### App Name

Zattoo

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

Would love it to work on the "TV" button on the App. When I click that button on the physical remote, it opens the Zattoo app, as it's the default TV app on my firetv.

**Comment by PRProd** [comment]
Maybe it's because I'm in the US, but when I try installing the "Zattoo" app on my device, the download page says "Unavailable". Without being able to download it for myself, it might take a while to get this added. Would you be willing to help me with some testing?

If we are lucky, I'll only need you to do this:

 - Launch the app on your device
 - In Home Assistant, click on Developer Tools -> States
 - Find your Fire TV entity by scrolling, or clicking the "set state" bar, and searching for it

Reply to this post with the contents found in the Attributes column or the "State attributes (YAML, optional)" box

If you'd like to tie this to your "TV" button, it is now possible as of the current release [v1.8.0](https://github.com/PRProd/HA-Firemote/releases/tag/v1.8.0).  You'll first need to create a Home Assistant script that causes your Fire device to switch to the Zattoo app, then you can tie it to the TV-Button as an override.  See the [Read Me](https://github.com/PRProd/HA-Firemote#button-overrides) file for details

**Comment by Icecoke7** [comment]
Hi @PRProd !

Sorry for the late response. Please find the contents below:

`adb_response: Starting: Intent { cmp=com.netflix.ninja/.MainActivity }
Warning: Activity not started, its current task has been brought to the front
hdmi_input: null
device_class: tv
friendly_name: Fire TV 127.0.0.1
supported_features: 22961
source_list: com.zattoo.player.firetv
app_id: com.zattoo.player.firetv
source: com.zattoo.player.firetv
entity_picture: /api/media_player_proxy/media_player.fire_tv_127_0_0_1?token=7af243115c5323eb6db3179d9f4ee66af77d815c6f803c0ab4650d19469bbfec&cache=1369254911.014336`

**Comment by PRProd** [comment]
Pre-release [v1.8.8](https://github.com/PRProd/HA-Firemote/tree/v1.8.8) is now available for testing.  Please download the new version and let me know if the Zattoo app shortcut is working as expected.  Thanks.

**Comment by PRProd** [comment]
Crossed my fingers and pushed this out officially before hearing from you.  Hopefully it works!  Please re-open this issue if the shortcut does not work.

This is now available in the Firemote official release v1.9.0
