### ISSUE TITLE
[New Device Support]: Roku

### ISSUE THREAD

**Issue by glassbase** [PRProd/HA-Firemote#208]
### Device Name

Any

### Which compatibility mode event number works BEST with your device?

None

### Additional Comments (optional)

Roku accepts HA remote.send_command service calls

**Comment by PRProd** [comment]
Greetings @glassbase!

I'm always looking to improve on this card, and there are others who have also expressed interest in adding Roku functionality.  Of course, there are others who also would like different devices to be added first.  That is why I use the poll over in discussion #41 to let the community decide on what should be next.

I just released Apple TV functionality yesterday, and I expect that for the next week or longer I will be fixing any reported bugs and adding Apple TV app requests as they flood in.  After all of that settles down, I will reset the poll in #41 and begin accepting votes for the next device.

I do all of this work voluntarily, and I have to buy the devices myself so I can do the required testing.  Because of those factors, I cannot estimate the amount of time it will be between the poll reset and the launch of the next device type.

For now, I'm going to close this issue and request that you keep an eye open over at Discussion #41 for your chance to vote.

Thanks!

**Comment by glassbase** [comment]
Will follow for new news. Thanks. Just coincidently found your project recently. Started integrating them into my dashboards.

**Comment by PRProd** [comment]
@glassbase - Feel free to share your dashboard(s) over at Discussion #129!  People love to look at what others have done
