### ISSUE TITLE
AppleTV 4th Gen, closing app need double tap

### ISSUE THREAD

**Issue by sypie** [PRProd/HA-Firemote#229]
### Describe the bug

For closing an app on the AppleTV 4th Gen (2015) the user needs to double tap on the "screen" button. After this an app can be swiped to top on the real remote. On the Firemote the user need to double tap the top button. To switch to another opened app the user only needs to tap the left/right button only once.

### To Reproduce

Open multiple apps, double tap the "screen" button.

### Expected Behavior

The expected behaviour is to only tap the top button once.

### Which Type of Device Do You Own?

Apple TV 4th Gen (2015)

### Troubleshooting Steps Completed

I did check the javascript file but couldn't find any leads to the number of button taps.

**Comment by PRProd** [comment]
Greetings @sypie!

I'm not sure if I completely understand what you are asking for, but I will do my best. 

Unfortunately, I do not (yet) have a way to detect a double tap or a button hold on the Firemote, so I'm unable to make the UI function exactly like the physical remote at this time.  However, because of this limitation (also discussed [in this thread](https://github.com/PRProd/HA-Firemote/discussions/200#discussioncomment-7214061)) I did create a way for the "double tap" menu to show up through the use of an optional button:

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/90db3fbd-7d15-4c29-a41f-472466dc3155)

If I understand your question properly, you are asking for the ability to simulate a double tap on the 'up' button to close an app from that menu, is that correct?

**Comment by sypie** [comment]
Hi PRProd,
Let me be clear at first: I tried the Firemote on a computer so a double tap works different than on a tablet or phone, what zooms in with double tap. On an Apple TV remote the double tapp on the arrow up doesn't have any function.

From now on I'm talking about the function on a pc.

To show you a short and clear example of how to close an app on the Apple TV: https://youtu.be/0nCH8DlmANs?si=iUri2yONlch30ZRK  The double tap on the button to change apps works perfect. It shows the app drawer. To close an app with te real remote you need to swipe left or right to select the app you want to close. After this you swipe up. That's all.

On the Firemote the swipe up function is a double tap. While the swipe left/right functions are only 1 tap on the left/right arrow. That's why it's (a bit) inconsistent.

Also for tablet of phone use the single tap on the up arrow to close an app could work like it shoud.

**Comment by PRProd** [comment]
Ahhh... I understand what you are saying now.  You are saying that it feels inconsistent to move through the app drawer with just one left or right button press, but it takes two presses on the up button to close an app in the drawer.

This behavior is actually identical to how the physical Apple TV remote behaves.  Apple decided to make it work this way, requiring two up presses to close an app, and only one press left or right to navigate.  Here is a video I just shot with mine:
https://www.youtube.com/watch?v=CSbraYSdyyI

I would be able to make a change to this behavior for Firemote if Home Assistant's AppleTV integration was able to reliably determine which app is open, but that is also not something that is available right now.

**Comment by sypie** [comment]
Ah, this makes sense. Apple decided to change the one tap from the old to the double tap in the new Apple TV. They didn't aks me for permission tough.

We'll guess this isn't a bug but it's an Apple feature.

**Comment by PRProd** [comment]
:laughing: They really should have asked you first!  LOL!
