### ISSUE TITLE
Showtime not working with nVidia Shield Pro (2015)

### ISSUE THREAD

**Issue by futomara** [PRProd/HA-Firemote#236]
### Describe the bug

The Showtime button does not launch the Showtime app

### To Reproduce

Adding the Showtime button to the remote and depressing it does not open Showtime

### Expected Behavior

Showtime does not launch

### Which Type of Device Do You Own?

Shield Pro (2015)

### Troubleshooting Steps Completed

I was able to find the latest working intent by creating a button override as follows: 

`  hamburger-button:
    service: androidtv.adb_command
    target:
      entity_id: media_player.android_tv_192_168_29_18
    data:
      command: am start -n com.showtime.showtimeanytime/com.showtime.showtimeanytime.activities.IntroActivity`

**Comment by PRProd** [comment]
Greetings @futomara!

I just found out that **Showtime** and **Showtime Anytime** are two different apps.  I wonder how long it's been like that?  

The app that you have is **Showtime Anytime**.  The shortcut in Firemote right now is for **Showtime**.  I'm working on adding **Showtime Anytime** to Firemote right now so that both will be available.

**Comment by futomara** [comment]
That's interesting. I assumed one could log in to the app depending on whether they had Showtime thru their TV provider or a separate Showtime Anytime subscription.  Learn something new everyday. :P

**Comment by PRProd** [comment]
I thought it was a strange choice too... not sure why they did it that way.  One of them says something about being part of Paramount+, so maybe that's why they have to remain separate? 

No matter what the reason, I just published Firemote Version [v3.0.5](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.5) which has separate buttons for each application, so everything should work as expected for you now.

Enjoy!

**Comment by futomara** [comment]
Much appreciated!
