### ISSUE TITLE
[New App Shortcut]: MrMC

### ISSUE THREAD

**Issue by kllngtme** [PRProd/HA-Firemote#241]
### App Name

mrmc

### Device Platform

Nvidia Shield

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=tv.mrmc.mrmc

### Application Info

a kodi like app

**Comment by PRProd** [comment]
Greetings @kllngtme!

The MrMC app is not a free download and it doesn't look like something I plan on using in my own personal life. I will need some additional information from you to move forward while avoiding having to buy the app for myself.

Please follow the step by step instructions provided in the article [Details for App Requests](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests), and post your results here.

**Comment by kllngtme** [comment]
adb_response: mSurface=Surface(name=tv.mrmc.mrmc/tv.mrmc.mrmc.Main)/@0x6ec0146
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xffd929e
  mCurrentFocus=Window{8c24771 u0 tv.mrmc.mrmc/tv.mrmc.mrmc.Main}
  mFocusedApp=AppWindowToken{dda8eef token=Token{19e6fce ActivityRecord{79dcc9 u0 tv.mrmc.mrmc/.Main t55}}}

**Comment by PRProd** [comment]
Thanks for your response @kllngtme!

Firemote version [v3.0.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.7) has just been published, and it contains the  app shortcut button for MrMC as you requested.  It should work, but since I wasn't able to test it before publishing I'll need you to let me know if something is wrong.

Enjoy!
