### ISSUE TITLE
[New App Shortcut]: tinyCam Monitor PRO

### ISSUE THREAD

**Issue by michaelrobgrove** [PRProd/HA-Firemote#248]
### App Name

TinyCam Pro

### Device Platform

Android/Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.alexvas.dvr.pro

### Optional Comments

Happy to help in a few days. Have Onn box and Fire TV.

**Comment by PRProd** [comment]
Greetings @michaelrobgrove!

The tinyCam Monitor PRO app is not a free download and it doesn't look like something I plan on using in my own personal life. I will need some additional information from you to move forward while avoiding having to buy the app for myself.

Please follow the step by step instructions provided in the article [Details for App Requests](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests), and post your results here.

**Comment by PRProd** [comment]
@michaelrobgrove 

It's been nearly two weeks since I've asked you about this, have you had a chance to review the [instructions I posted](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices) yet?

**Comment by PRProd** [comment]
@michaelrobgrove ~
I'm going to temporarily close this issue for now while I wait for your reply.  Please reply here when you are available to help and have the answer to my question, and I will happily re-open the issue and get back to work on it.
