### ISSUE TITLE
Card does not show up

### ISSUE THREAD

**Issue by hackintoshlover** [PRProd/HA-Firemote#266]
### Describe the bug

Running the latest home assistant os on raspberry pi cm4.
Connected my apple tv to home assistant via integration.
Followed every step mentioned on the github page and installed repo to home assistant.
But when searching for firemote card in lovelace ui, its not available.
Reinstalled but still the same issue.
Help needed.

### To Reproduce

Nothing special

### Expected Behavior

Nothing special

### Which Type of Device Do You Own?

Raspberry pi cm4

**Comment by PRProd** [comment]
Greetings @hackintoshlover!

I've been getting this question a lot lately, so I think I'm going to make a wiki article about it and link it from the [README.md](https://github.com/PRProd/HA-Firemote#readme) and the [FAQ](https://github.com/PRProd/HA-Firemote#faq) sections.

The problem that you are seeing is very likely due to a sticky Home Assistant cache.  Even when you do all of the right things to refresh your browser, clear the cache through the browser tools, or clear the cache of your Home Assistant companion app it can sometimes STILL be a cache issue.  I'm not sure what the Home Assistant devs did to make their cache so persistent, but I can guarantee you that they did it so that we could all enjoy the tremendous speed increase a good caching system provides.

So, how do we reliably clear the cache?  If you are using a web browser to interact with Home Assistant, you can try to [clear your browser cache](https://www.hellotech.com/guide/for/how-to-clear-cache-chrome-safari-firefox-edge) first through the conventional methods.  If that doesn't work and/or if you are using the Android or iOS companion app then I would suggest reading through [this "refreshing" discussion](https://github.com/PRProd/HA-Firemote/discussions/74#discussioncomment-5618842) to find what will work for your situation.

After successfully clearing your cache, if you have the Firemote card installed you will see it in the **+ ADD CARD** menu under **Custom: Firemote Card**

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/ff210856-b14a-4482-a9eb-93fe1542c2a6)

**Comment by hackintoshlover** [comment]
Thanks for the superfast response.
I will try it out at the earliest and get back to you.

**Comment by PRProd** [comment]
@hackintoshlover ~ Have you had an opportunity to test this again?

**Comment by hackintoshlover** [comment]
Hey Nelson,
I have a power outage in my locality due to transformer breakdown.
Should be fixed by this week.
Will try and update you asap.
Thanks.

**Comment by PRProd** [comment]
I will need some more details from you.

Did you attempt to install HA-Firemote through [HACS](https://peyanski.com/how-to-install-home-assistant-community-store-hacs/) or by installing manually?

### If you used HACS
When you search for it again in HACS, do you still see the **DOWNLOAD** button?
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/4abada66-67b8-4862-8829-ac827a717e2d)
If you do see that button, that means that you haven't actually downloaded it.  Click the download button and try the setup again.

### If you installed manually
Did you accomplish [these important steps](https://github.com/PRProd/HA-Firemote#or-install-manually) from the instructions?
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/04affc1f-4d2e-43f5-8cc7-c2bb24e415e1)

If so, is your Home Assistant environment properly set up to access files in the /www directory?  To test this, try going to this address: Change the items inside { the brackets } to fit your situation.
 - http:/{ Your HA Address }/local/HA-Firemote.js

**Comment by hackintoshlover** [comment]
I installed using HACS.
I can access the /www/directory and all the HA-Firemote files and folders are present in it. See image below.
The path is /homeassistant/www/community/HA-Firemote
![Screenshot (280)](https://github.com/PRProd/HA-Firemote/assets/40655406/ce6d99ec-8a14-44ea-b2ec-fd624d09d085)

Typing http://{ Your HA Address }/local/HA-Firemote.js this in a browser yeilds 404: Not Found.

I don't see download button again for Firemote but i do get an error upon restart. See image below.
![Screenshot (279)](https://github.com/PRProd/HA-Firemote/assets/40655406/7e00b956-b851-4fee-90e3-311b19c3ce6b)

Have i done something wrong?

**Comment by PRProd** [comment]
https://hacs.xyz/docs/faq/status_not_loaded/

**Comment by PRProd** [comment]
@hackintoshlover ~

Since we have solved the issues with your Firemote HACS installation, I'm going to close this issue.  If you experience any issues with the Firemote card itself, please feel free to let me know.  Thanks.

-Doug
