### ISSUE TITLE
[New App Shortcut]: WaipuTV

### ISSUE THREAD

**Issue by github-sunny** [PRProd/HA-Firemote#27]
### App Name

WaipuTV

### Can this app be freely downloaded through official means?

- [X] Yes

**Comment by PRProd** [comment]
@github-sunny  - Maybe it's because I'm in the US, but when I try searching for the "WaipuTV" app on my device, there are no results. Did you sideload this app, or is it available in your region just by searching?  Without being able to download it for myself, it might take a while to get this added. Would you be willing to help me with some testing?

If we are lucky, I'll only need you to do this:

Launch the app on your device
 - In Home Assistant, click on Developer Tools -> States
 - Find your Fire TV entity by scrolling, or clicking the "set state" bar, and searching for it
 - Reply to this post with the contents found in the Attributes column or the "State attributes (YAML, optional)" box

**Comment by github-sunny** [comment]
Hello Doug,

Thanks for the fast reply.

So, WaipuTV is here a normal app for the FireTV, no Sideload or so. I'm
living in Germany.

Here the Attributes:

source_list: Waipu TV
device_class: tv
entity_picture:
/api/media_player_proxy/media_player.fire_tv_192_168_178_37?token=4271ea327136d53264847190e38e807c8c077975787644d6fdb543f82402ef29&cache=1672773607.201563
friendly_name: Fire TV 192.168.178.37
supported_features: 22961
app_id: de.exaring.waipu.firetv.live
source: Waipu TV
adb_response: Starting: Intent { act=android.intent.action.MAIN
cat=[android.intent.category.LAUNCHER]
cmp=com.amazon.firebat/.deeplink.DeepLinkRoutingActivity }


Am Di., 3. Jan. 2023 um 20:04 Uhr schrieb Doug Nelson <
***@***.***>:

**Comment by PRProd** [comment]
Please download pre-release [v1.9.2-beta](https://github.com/PRProd/HA-Firemote/releases/tag/v1.9.2-beta) to test if the WaipuTV app shortcut is working properly for you.  Since I'm not in Germany, I am unable to test this myself.

**Comment by github-sunny** [comment]
Thanks, it works!


Doug Nelson ***@***.***> schrieb am Di., 3. Jan. 2023, 20:48:

**Comment by PRProd** [comment]
Great! [v1.9.2](https://github.com/PRProd/HA-Firemote/releases/tag/v1.9.2) is now an official release, including this new app shortcut.
