### ISSUE TITLE
[Feature Request]: Toggle and Multiple enity control.

### ISSUE THREAD

**Issue by hackintoshlover** [PRProd/HA-Firemote#277]
### Feature Request

1) Toggle Function for power and mute button
I have my apple TV connected to home assistant and controlled via firemote card.
To control power toggle in home_assistant i use button override function and call media_player.toogle and it toggles my apple tv power on and off function.

Can you add same feature for mute as well.
Scouring around the internet i found various scripts and tried all of them.
But toggling is flaky either it mutes or unmutes.

2) Press to increase/decrease volume.
Currently if i want to increase or decrease volume, i have to keep tapping to increase or decrease volume.
Can you add a function wherein it's like normal remotes wherein the volume keeps increasing until you leave the button.
 
2) Add an option to control multiple entity through a single button.
I have my set top box hdmi output going to yamaha av receiver input and it's output going to my screen.
Now when i press power button, i want all three of them to turn on and off together.
The problem is when i try to add all three entities in one button function, the firemote card gives me error saying duplicate entry and i card.
Attached are pictures below for your reference.
![WhatsApp Image 2023-12-19 at 11 42 40 (1)](https://github.com/PRProd/HA-Firemote/assets/40655406/cf9e0182-a190-483b-be1f-7892464d3a22)
![WhatsApp Image 2023-12-19 at 11 42 40](https://github.com/PRProd/HA-Firemote/assets/40655406/c7d09b75-58de-4bc7-8b8b-31d1dfa8e1d4)

**Comment by hackintoshlover** [comment]
Hi Nelson,
Thanks for replying superfast.

> I'm curious about why you needed to make a button override for your power button. There is [existing logic](https://github.com/PRProd/HA-Firemote/blob/90444b419aaab7b00debe81fba3d32c49b9b98c8/dist/HA-Firemote.js#L10183-L10195) that should do that work without an override. At least, it works properly on my Apple TV device. Does it not work properly on yours?

Yes it does not work on mine, hence i used button override to toggle my receiver power on and off.
I guess it might be due to my setup.
Apple TV>Yamha Receiver>Samsung Screen.
CEC is enabled on all of them but it does not work.
I can live with it for now. Probably updating my yamaha firmware might help.

> The scripts that you've been trying, I assume that you are using them to mute / unmute your media_player.conference device? It's possible that the advice I give below for question 3 will help you with this one as well. If not, I can help you some more.

Script 1:

mute_toggle:
  alias: Toggle media_player mute
  fields:
    entity_id:
      description: Entity id of the media_player
      example: media_player.media_room
  sequence:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ state_attr(entity_id, ''is_volume_muted'')
          == false }}'
      sequence:
      - service: media_player.volume_mute
        data:
          is_volume_muted: true
        target:
          entity_id: '{{ entity_id }}'
    default:
    - service: media_player.volume_mute
      target:
        entity_id: '{{ entity_id }}'
      data:
        is_volume_muted: false
  mode: single

Script 2:

yamaha_toggle:
  sequence:
  - service: media_player.volume_mute
    target:
      entity_id: media_player.media_room
    data:
      is_volume_muted: "{{ not state_attr('media_player.media_room', 'is_volume_muted') }}"

And many others but none of them work.
Either the scripts mute or unmute both don't toggle.
I did change necessary fields with my player id.

> Unfortunately, as of right now I cannot. The same limitation also exists for "long press" button events. I have not yet come up with an elegant way to make this work. It's on my list of things to get back to, but right now I don't have a solution.

I'll be eagerly waiting for this feature. Just not a fan of builtin home assistant slider.
What if we could via a script import the slider and mute function of home assistant's built-in ui/entity something.
Like when i add apple tv integration, it adds two cards to my dashboard.
One of which allow to toggle power, control mute, volume.
I might be speaking nonsense at this point but i guess you got the idea.

> This is already possible using a button override to trigger a Home Assistant script. All we need to do is write the script.

Thanks for the the huge explanation.
I already tried all of these.
The problem is as i highlighted in the images posted in my issue.
As soon as i add multiple entities in home assistant, i get file check warning that says "duplicate entries found" and doesn't allow me to save the same.

Guess i need to update my home assistant setup which i am trying to avoid since some integrations break on update.
But i guess it has to be that way.

A huge thanks to you for making this card, it really simplifies things since atleast my brain is wired to look and feel of physical remote.
Please make the volume thing possible. It will be cherry on the cake.

I'll try out rest of the things and get back to you at the earliest.
Thanks.

**Comment by PRProd** [comment]
@hackintoshlover ~

Thank you for your reply.  I think we can solve most of this for you.
<br>

### Press and Hold remote button repeat request:
I'm going to have to say no to this one right now while I work on rolling out [Roku support](https://github.com/PRProd/HA-Firemote/discussions/275) and spending some time with my family this holiday season.  When I get back to this, I'll open a new issue and tag you in it so you can keep track of the progress.

<br><br>

### Power on/off multiple entities:
>Thanks for the the huge explanation.
I already tried all of these.
The problem is as i highlighted in the images posted in my issue.
As soon as i add multiple entities in home assistant, i get file check warning that says "duplicate entries found" and doesn't allow me to save the same.

You might not have read my explanation closely enough.  You did **not** try it the way that I presented.  

Your Firemote card YAML:
```yaml
button-overrides:
  power-button:
    service: media_player.toggle
  target:
    entity_id: media_player.conference
    entity_id: media_player.apple_tv
```
My working Firemote card YAML example:
```yaml
button_overrides:
  power-button:
    script: toggle_media_power
```
Your example Firemote card YAML is invalid YAML syntax because there are two **entity_id** entries in the same block.  To accomplish what you want to do will require writing a Home Assistant script _outside_ of the Firemote card, and telling the Firemote card to run that Home Assistant script when the power button is pressed.

If you follow the instructions I gave in my [previous post](https://github.com/PRProd/HA-Firemote/issues/277#issuecomment-1863244759) you should be able to accomplish this task.

<br><br>

### Toggle Receiver's Mute Function:
>And many others but none of them work.
Either the scripts mute or unmute both don't toggle.
I did change necessary fields with my player id.

Since you are able to mute or unmute through Home Assistant, we can make a script similar to the one for the power button.  If you send me an example of a command that will mute, and an example of a command that will unmute, I can write it for you (even though it has nothing to do with Firemote :smile: ) 

Once that script is written and it works as expected, it's simple to tie it to your Firemote's mute button:
```yaml
button_overrides:
  mute-button:
    script: { YOUR NEW MUTE TOGGLE SCRIPT NAME }
```

<br><br>

I hope this clears up any confusion.  I apologize if I wasn't clear enough in my initial response.  Good luck!  

-Doug

**Comment by hackintoshlover** [comment]
> Press and Hold remote button repeat request:
I'm going to have to say no to this one right now while I work on rolling out https://github.com/PRProd/HA-Firemote/discussions/275 and spending some time with my family this holiday season. When I get back to this, I'll open a new issue and tag you in it so you can keep track of the progress.

I totally understand that and will be eagerly waiting.

> You might not have read my explanation closely enough. You did not try it the way that I presented.
I'll try that for sure.

> Since you are able to mute or unmute through Home Assistant, we can make a script similar to the one for the power button. If you send me an example of a command that will mute, and an example of a command that will unmute, I can write it for you (even though it has nothing to do with Firemote 😄 )

I use homeassistant's built-in service "media_player.volume_mute" entity_id "media_player.conference" "is_volume_muted" true (to mute)
"media_player.volume_mute" entity_id "media_player.conference" "is_volume_muted" false (to unmute)

> I hope this clears up any confusion. I apologize if I wasn't clear enough in my initial response. Good luck!

Not your fault. I still have many things to learn.

**Comment by PRProd** [comment]
@hackintoshlover

Since I haven't heard anything new from you about this in the last two weeks, I'm going to close this issue.  Please feel free to reach out again if you have any further questions.

-Doug
