### ISSUE TITLE
[Feature Request]: Onscreen keyboard for appletv users

### ISSUE THREAD

**Issue by jdemarc2** [PRProd/HA-Firemote#280]
### Feature Request

I currently love this setup however it is not very useful for me as I have the appletv remote on my iphone. I would fully use this setup if it offered an onscreen keyboard that activates whenever it goes to a search bar which is what the apple tv remote on the iphone does.

**Comment by PRProd** [comment]
Greetings @jdemarc2,

I completely understand why you want this feature, but unfortunately due to the way the Firemote card functions it will not be possible to implement at this time.

In the [Firemote wiki](https://github.com/PRProd/HA-Firemote/wiki) the section [How Does Firemote Send commands to my devices?](https://github.com/PRProd/HA-Firemote/wiki#how-does-firemote-send-commands-to-my-devices) states:
> ### How Does Firemote Send commands to my devices?
> Firemote isn't an integration, it's just a Home Assistant (lovelace) card that is designed to interact with your media player devices in the most efficient way possible.  EVERYTHING that Firemote can do, you could do too through scripts and commands.

Since keyboard support is not something that is included in the [Home Assistant Apple TV integration](https://www.home-assistant.io/integrations/apple_tv), it is not possible to add this feature to Firemote.

I hope this explanation helps.
