### ISSUE TITLE
[Feature Request]: Add swipe actions for apple TV remote

### ISSUE THREAD

**Issue by depunkar** [PRProd/HA-Firemote#281]
### Feature Request

Request: Add directional swiping for Apple TV remote card. 

Details: On Apple TV remote (1st gen), there is functionality to swipe up, down, left, and right on the touchpad. The action from these swipes varies based on the app that user is interacting with. Requesting similar swiping feature to be implemented in the Apple TV remote card.

**Comment by PRProd** [comment]
Greetings @depunkar

I know that this isn't "swiping", but did you happen to notice that there are D-Pad style controls hidden inside that section of the remote?  This is where they are located:
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/067c736c-64bd-4a8c-985b-acf56b8fef7c)

Also, you do have the ability to choose ANY remote style you'd like, so if you wanted to use an Apple TV style remote that has the D-Pad buttons built in, you could select **Apple TV Remote Style 1** or **Apple TV Remote Style 2** from the dropdown menu:

| Selector | Style 1 | Style 3 |
| ----------  | --------- | ---------  |
| ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/0ba115d4-11bf-4b88-b39a-5245926b4bc3) |  ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/d206eb31-4567-4d4e-afc5-7a5e82bb36e6) | ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/0ca1c4ca-1601-4990-929b-df5b22606269) |

I completely understand why you want this swipe feature added, but unfortunately due to the way the Firemote card functions it will not be possible to implement at this time.

In the [Firemote wiki](https://github.com/PRProd/HA-Firemote/wiki) the section [How Does Firemote Send commands to my devices?](https://github.com/PRProd/HA-Firemote/wiki#how-does-firemote-send-commands-to-my-devices) states:
> ### How Does Firemote Send commands to my devices?
> Firemote isn't an integration, it's just a Home Assistant (lovelace) card that is designed to interact with your media player devices in the most efficient way possible.  EVERYTHING that Firemote can do, you could do too through scripts and commands.

Since swipe support is not something that is included in the [Home Assistant Apple TV integration](https://www.home-assistant.io/integrations/apple_tv), it is not possible to add this feature to Firemote.

I hope these alternatives, and this explanation helps.
