### ISSUE TITLE
Plex and SmartTube shortcuts don't work. 

### ISSUE THREAD

**Issue by TherisValayrin** [PRProd/HA-Firemote#285]
### Describe the bug

I'm using a Firestick 4k Max, 2023 edition, with default settings. When attempting to assign custom apps to the App Launch section, Plex doesn't launch (and weirdly enough is the only name that is lowercase in the ENTIRE drop down menu that I saw, not sure if that's important), and SmartTube Next doesn't work either. These are in spots 1 and 3 respectively.

I know that the customization works as I added Disney+ and Dropout to these menu buttons and those are functional (2 and 4)
![image](https://github.com/PRProd/HA-Firemote/assets/61668240/446adb7a-ae51-480f-b579-1beda9ce5991)

### To Reproduce

Assign Plex, Disney+, STube, and Dropout to your app launch buttons. Test.

### Expected Behavior

Launch all apps when pressed

### Which Type of Device Do You Own?

Firestick 4k Max, 2023 edition

### Troubleshooting Steps Completed
Tried switching around layout of buttons, and unpairing the integration and back again, but with some of those already working I didn't have much hope for that working anyways

**Comment by PRProd** [comment]
Hey, thanks @TherisValayrin!

I hadn't considered this unfortunate possibility after discovering some of the differences with the latest Firestick models, so I sincerely appreciate that you brought it to my attention!

I have been able to fix this, but since I am in a development cycle for [Roku support](https://github.com/PRProd/HA-Firemote/discussions/275) this is not yet available in the official Firemote latest release.  However, if you'd like to use it now, it is available in the latest beta version [V3.2.0b3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0b3) which I have just published.

If you'd like, I can let you know when these changes have been published into the latest official release.

-Doug

**Comment by TherisValayrin** [comment]
Hey Doug, just as a heads up that worked! Took it all a second to realize what was going on, after a boot up, but worked like a charm! 

Thanks for the expeditious fix!

**Comment by TherisValayrin** [comment]
Sorry it's closed!

**Comment by TherisValayrin** [comment]
Issues resolved on my end

**Comment by camelcamro** [comment]
hmm, strange ... is not working for me .... not sure, whats wrong ...
as i have the newest version installed.

the debug adb is giving me:

adb_response: mSurface=Surface(name=com.liskovsoft.smarttubetv.beta/com.liskovsoft.smartyoutubetv2.tv.ui.browse.BrowseActivity)/@0x9bcab80
  mInputMethodTarget in display# 0 Window{9bb67f9 u0 com.liskovsoft.smarttubetv.beta/com.liskovsoft.smartyoutubetv2.tv.ui.browse.BrowseActivity}

maybe the new smarttube is to new for the key ?
(smarttube: [21.56 Beta](https://github.com/yuliskov/SmartTube/releases/tag/21.56)
and HA-Fireremote: 3.2.7

any ideas ?
