### ISSUE TITLE
[Feature Request]: Add color and style config options to AL1 and AL2 

### ISSUE THREAD

**Issue by ilianhris** [PRProd/HA-Firemote#290]
### Feature Request

Hello. How can change default background on Launcher  also remove borders around the buttons. Thanks.

**Comment by PRProd** [comment]
Greetings @ilianhris!

You'll be happy to know that this ability already exists!  Originally, this was suggested in #148 and had its latest feature update on October 2023 in Firemote version [v3.0.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.3).

If you review the [README.md](https://github.com/PRProd/HA-Firemote/blob/main/README.md) file, in the [YAML Card Setup Options](https://github.com/PRProd/HA-Firemote/blob/main/README.md#yaml-card-setup-options) section you can find the following entry:

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/9e225610-afb0-47eb-bd65-a140ca9aab70)

To use this on your Firemote card, simply add the following line to your Firemote card's YAML config:
```YAML
use_theme_background: true
```

I hope this helps!  Enjoy!

-Doug

**Comment by ilianhris** [comment]
Hello. Thanks fot the fast response. Was able to change the background color with use_theme_background: true but it didn't remove the borders around the buttons. And also is it possible to set background color that I choose?
![IMG_2455](https://github.com/PRProd/HA-Firemote/assets/112797248/b53d0cf8-15cb-4718-a10b-975da206b31f)

**Comment by PRProd** [comment]
@ilianhris,

Currently, there is not a way to use a custom color background, or to hide the frame around that button group.  Would you like for me to change the name of this feature request from **Change background to match my theme** to something that better describes these two requests?

**Comment by ilianhris** [comment]
Yes you can change the name. Can I remove that frame and background from.js file?

**Comment by PRProd** [comment]
@ilianhris - Absolutely!  That's the joy of open source software!  Once you download that .js file into your Home Assistant instance, you can make as many changes to it as you'd like.

The only drawback to doing that yourself is that when a new version of Firemote is released, downloading that update will overwrite the custom changes you made inside your own files.  Since the Firemote project started, I've published an excessive **114** releases so far.  These things come fast because I'm always trying to innovate.

So, two options here:
 1. You choose to make these changes to your local system only, and we close this feature request
 2. I work on this feature request, with the eventual goal of making background colors and border framing into user selectable options in a future core release of Firemote

I will let you decide.

**Comment by ilianhris** [comment]
Hello. Gonna be better if there is that featur and gonna be thankful if you add it. But can I change it locally until then?

**Comment by PRProd** [comment]
Yes.  As I said before, you are free to do whatever you'd like in your own local Home Assistant environment.

**Comment by ilianhris** [comment]
I need a little help... what i have to change exactly.

**Comment by PRProd** [comment]
I have just published Firemote beta version [v3.2.3b1](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.3b1) for you to download and test.

This beta version contains new items in the visual editor that you have requested:

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/b1bd6bc4-1a5e-478f-85b8-cffb9732aced)

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/338334b2-58a3-498c-9c44-6a3be45b85bf)


Please download and test this version, and let me know what you think.

Thanks.

**Comment by PRProd** [comment]
This has been added to the latest release, Firemote version [v2.3.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.3)

Enjoy!
