### ISSUE TITLE
[New Language Support]: Hebrew עברית

### ISSUE THREAD

**Issue by tomerbs** [PRProd/HA-Firemote#292]
### Language Code

he

### Translation Chart

```text
01. App Launch Button => לחצן הפעלת אפליקציה
02. App Launcher Relative Scale => קנה מידה יחסי של לחצן הפעלת אפליקציה
03. Apple Computers => מחשבי אפל
04. Apple Music => אפל מיוזיק
05. Apple Photos => אפל תמונות
06. Associated => משויך
07. bottom => למטה
08. Compatibility Mode => מצב תאימות
09. Computers => מחשבים
10. Default for => ברירת מחדל עבור
11. Device Family => משפחת מכשיר
12. Device Model => דגם מכשיר
13. Device Name Text Color => צבע טקסט של שם המכשיר
14. Entity => ישות
15. Function: Control Center => פונקציה: מרכז בקרה
16. Function: Find My Remote => מצא את השלט
17. Function: Mute => פונקציה: השתק
18. Function: Next => פונקציה: הבא
19. Function: Previous => פונקציה: הקודם
20. Function: Reboot => פונקציה: איתחול
21. Function: Search => פונקציה: חיפוש
22. Function: Settings => פונקציה: הגדרות
23. Function: Skip Backward => פונקציה: דלג אחורה
24. Function: Skip Forward => פונקציה: דלג קדימה
25. Function: Switch Apps => פונקציה: החלף אפליקציה
26. hidden => מוסתר
27. Music => מוסיקה
28. Name Position => מיקום השם
29. optional => אופציונלי
30. Photos => תמונות
31. Remote Style => מראה השלט
32. Scale => קנה מידה
33. Settings => הגדרות
34. Search => חיפוש
35. top => למעלה
36. Visible Device Name => שם מכשיר גלוי
```

**Comment by PRProd** [comment]
@tomerbs ~ THANK YOU!

So... right to left is interesting to me.  I can see now that changing the Home Assistant language also causes my remote layouts to move into a right to left orientation as well... and it totally breaks the Fire TV remotes' DPad layout.  I will need to work on that.  :smile: 

Focusing on the translations now, I would like you to review the following screenshots and guide me on what needs adjustment.  Whatever you see, big or small, I want to make it right.  Thank you in advance!

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/b3ab2602-1d56-4987-a78f-6cde9fe75822)
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/c506bd38-3e4b-4aa6-8ad0-6fe6129b98e9)
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/64b04a7b-9c71-4889-8ef1-c5a7b956058b)

**Comment by PRProd** [comment]
@tomerbs 

It looks like I have a few more for you, if you don't mind:
```
 Function: Volume + => 
 Function: Volume - =>
 Function: Channel + =>
 Function: Channel - =>
```

**Comment by tomerbs** [comment]
Function: Volume + =>  + פונקציה: ווליום
 Function: Volume - => - פונקציה: ווליום
 Function: Channel + => + פונקציה: ערוץ
 Function: Channel - => - פונקציה: ערוץ

**Comment by tomerbs** [comment]
Hi,

You need to fix only the first one, please see the picture attached.

Best Regards
Tomer

**Comment by PRProd** [comment]
@tomerbs ~ the image that you attached did not post to this issue thread, so I did not receive it.  Would you be able to post it directly to https://github.com/PRProd/HA-Firemote/issues/292 for me?

**Comment by tomerbs** [comment]
Here you go
![1](https://github.com/PRProd/HA-Firemote/assets/33035719/b2ba188b-bb0c-4d7a-b6a2-0b9f70839b61)

**Comment by PRProd** [comment]
Thank you for all of your help @tomerbs!

I wanted you to know that this is now complete, and is in the current Firemote beta release version [3.2.0b6](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0b6).  Feel free to download the beta, or you can also wait until it is published in the next official Firemote release.

Enjoy!

**Comment by tomerbs** [comment]
Hi Doug,

no problem mate, I will check it tomorrow and advise.

**Comment by PRProd** [comment]
@tomerbs ~

This has been pushed to the official Firemote release version [v3.2.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0).  The issue is closed for now, but feel free to re-open it if you find anything else that should be changed.  Thanks again!

-Doug

**Comment by tomerbs** [comment]
Hi, I've installed the new version and set the HA language to Hebrew but when entering the card settings they are still in English.
Do I need to change something in the card configuration to be able to see the translation to Hebrew?

**Comment by PRProd** [comment]
There could be a couple of things going on here, so I'll mention everything and hopefully one of these will do the trick for you.
<br><br>
## Setting Home Assistant Language
There are two places where this must be done.  I don't completely understand why this is the case, or how the HA team decides between which parts receive a **system** language and which parts receive a **user** language, but both exist.  If you know the answer to this, I'd love to understand!
<br><br>
### Setting the System Language
 1. Click on **Settings**
 2. Click on **System**
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/fde4aaf5-ca91-450e-b9dc-827ba17e3757)
 3. Click on **General**
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/f09bf641-55be-498e-83a3-367eac3a2717)
 4. Open the **Language** dropdown menu
 5. Select Hebrew
 6. Click the **UPDATE** button
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/8d8f4b05-e333-4944-8cf0-d51b458efddd)

<br><br>
### Setting the User Language
This is the setting that the Firemote card is using to decide on translations.  Setting this is simple:
 1. Click on your user name
 4. Open the **Language** dropdown menu
 8. Select Hebrew
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/7c68a939-57f6-4f04-b576-994d0344d9b1)

<br><br>
## Dealing with sticky cache
The other issue that comes up fairly often is after downloading an update, nothing seems to change because your device is showing an older cached copy instead of the new version.  I wrote an article in the [Firemote Wiki](https://github.com/PRProd/HA-Firemote/wiki) called [Force a Refresh](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) that can guide you through the process of overcoming a very sticky cache.

Another helpful tool to help you determine if you are on the most current Firemote version is actually built right in.  Simply add the following line to your YAML config:
```YAML
  show_version_number: true
```
Adding that option to your Firemote config will display the current Firemote version with your card in the UI.

<br><br>
## Putting it all together
Following these methods, you should arrive at a screen like this when editing your Firemote card.  The option labels are shown in Hebrew, and your current Firemote version number is displayed with the card.
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/82ff4392-ea48-45ac-875d-79361944b92a)

<br><br>

I hope this helps!

-Doug

**Comment by tomerbs** [comment]
Yes, it helps and it looks as it should.
Thanks.

**Comment by PRProd** [comment]
You're welcome!  Thank YOU for your help with this!
