### ISSUE TITLE
[New App Shortcut]: Stb Emu pro

### ISSUE THREAD

**Issue by sidd905** [PRProd/HA-Firemote#302]
### App Name

Stb Emu Pro

### Device Platform

NVIDIA Shield

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.mvas.stb.emu.pro

### Application Details

IPTV application

**Comment by PRProd** [comment]
Greetings @sidd905!

Your app request is for a paid app which I do not own.  Because of this, I need you to follow [these instructions For Fire TV, Chromecast, NVIDIA Shield, Xiaomi Mi, and other Android based devices](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices) and reply here with the results.

Without that information, I will be unable to proceed with your request.  Thank you for your understanding.

-Doug

**Comment by PRProd** [comment]
Hand drawn SVG artwork has been completed.  (this one was kind of fun to do!)
![stbemu-pro](https://github.com/PRProd/HA-Firemote/assets/25486599/51f59847-0d14-4d4c-9fed-df5d3033475e)

**Comment by PRProd** [comment]
@sidd905 ~

Just a reminder that your request is currently **on hold** until I receive your response.
 
> Your app request is for a paid app which I do not own. Because of this, I need you to follow [these instructions For Fire TV, Chromecast, NVIDIA Shield, Xiaomi Mi, and other Android based devices](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices) and reply here with the results.
> 
> Without that information, I will be unable to proceed with your request. Thank you for your understanding.

**Comment by PRProd** [comment]
@sidd905 ~

This issue will be closed within the next few days if I do not hear back from you.  Please let me know.  Thanks.
