### ISSUE TITLE
[New Language Support]: Polish

### ISSUE THREAD

**Issue by lukazareba** [PRProd/HA-Firemote#315]
### Language Code

pl

### Translation Chart

```text
01. App Launch Button => Przycisk Aplikacji
02. App Launcher Relative Scale => Skalowanie
03. Apple Computers => Komputery Apple 
04. Apple Music => Apple Music
05. Apple Photos => Apple Photos
06. Associated => Powiązania
07. bottom => dół
08. Compatibility Mode => Tryb zgodności
09. Computers => Komputery
10. Default for => Standardowe dla
11. Device Family => Rodzina urządzeń
12. Device Model => Model urządzenia
13. Device Name Text Color => Nazwa urządzenia, kolor tekstu 
14. Entity => Encja
15. Function: Channel + => Kanał +
16. Function: Channel - => Kanał -
17. Function: Control Center => Centrum sterowania
18. Function: Find My Remote => Znajdź pilot 
19. Function: Mute => Wycisz
20. Function: Next => Następne
21. Function: Previous => Poprzednie
22. Function: Reboot => Restart
23. Function: Search => Szukaj
24. Function: Settings => Ustawienia
25. Function: Skip Backward => Przewiń do tyłu
26. Function: Skip Forward => Przewiń do przodu
27. Function: Switch Apps => Przełącz aplikację
28. Function: Volume + => Podgłoś
29. Function: Volume - => Przycisz
30. hidden => Ukryte
31. Music => Muzyka
32. Name Position => Nazwa pozycji
33. optional => opcjonalne
34. Photos => Zdjęcie
35. Remote Style => Styl pilota 
36. Scale => Skala
37. Settings => Ustawienia
38. Search => Szukaj
39. top => góra
40. Visible Device Name => Nazwa urządzenia
```

**Comment by PRProd** [comment]
Thanks @lukazareba!

I translated some of your translations back to English, and I'm concerned that some of them might have lost their intended meaning.  Because of that concern, I made some adjustments.  I don't really expect that they are all correct / better than what you had, after all, you know better than I would know!

Can you review these images and let me know what needs to be adjusted?  Thanks.

### Main UI
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/de36c496-d24b-43de-a86f-2e8209d461eb)
<br><br>

### Position Dropdown Menu
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/a749f7f7-3e66-4607-b05f-68c114207f37)
<br><br>

### App Launcher 2
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/19bf728a-cfc2-4dd6-8bf5-4c6f87cb2735)
<br><br>

### Functions in App Launcher Menus
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/bd067f2b-02f1-48ea-8303-9cacd27b8282)

**Comment by PRProd** [comment]
I also just published this translation into the latest Firemote version [v3.2.2](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.2), so you can take a look at the Firemote UI menus on your own system if you'd prefer.

I will still keep this issue open until I hear back from you and we work out all of the final details.  Thanks!
