### ISSUE TITLE
[New App Shortcut]: RTL+

### ISSUE THREAD

**Issue by TheNightmanX** [PRProd/HA-Firemote#330]
### App Name

RTL+

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/de/app/rtl/id1057991212

### Application Details

custom_launchers:
  - friendly_name: RTL+
    background: white
    image_path: https://upload.wikimedia.org/wikipedia/commons/f/f4/RTL%2B_Logo_2021.svg
    service: media_player.select_source
    target:
      entity_id: media_player.appletv
    data:
      source: RTL+

### Optional Comments

Using the code above and it is working

**Comment by PRProd** [comment]
Greetings @TheNightmanX!

I'm guessing that you are interested in the RTL+ German version, and not the RTL+ Hungary version, is that right?  I'm unsure because the link that you provided is for the German version, but the logo that you provided is the logo for the Hungary version.

| App Name         | Platform                 | Link                                                                                                         | Logo |
| --------------         | -----------                 | -----                                                                                                          | ------- |
| RTL+                 | iOS Store               | https://apps.apple.com/de/app/rtl/id1057991212                                    | ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/6100c833-64f5-444e-afa2-0d2147613b07) |
| RTL + Hungary | iOS Store               | https://apps.apple.com/us/app/rtl-magyarorsz%C3%A1g/id561704622 | ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/0fcdaf65-df8f-439e-8f58-a0d758144aa0) |
| RTL+                 | Google Play Store |  https://play.google.com/store/apps/details?id=de.rtli.tvnow                    |![image](https://github.com/PRProd/HA-Firemote/assets/25486599/22f41a96-401c-4f8f-bb35-b2be253c75d8)|
| RTL+ Hungary  | Google Play Store  | https://play.google.com/store/apps/details?id=hu.telekomnewmedia.android.rtlmost |![image](https://github.com/PRProd/HA-Firemote/assets/25486599/04d3e2a5-e274-4ec5-9b0e-4de09d6b0b43)|

**Comment by TheNightmanX** [comment]
Yes indeed I meant the German version. Sorry for the misleading information.

**Comment by PRProd** [comment]
No problem!  I just wanted to make sure that I got it right!

I think that I'll include both versions

**Comment by PRProd** [comment]
@TheNightmanX ~

Firemote version [v3.2.6](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.6) has just been published, and it contains the app launcher that you requested, as well as one for RTL+ Hungary.  Enjoy!

-Doug
