### ISSUE TITLE
[New App Shortcut]: Go3 TV

### ISSUE THREAD

**Issue by reinuke** [PRProd/HA-Firemote#335]
### App Name

Go3 TV

### Device Platform

Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=tv.go3.android.tv

### Application Details

Android TV - Xiaomi Mi Box S - Google Play Store app

adb_response: mSurface=Surface(name=tv.go3.android.tv/pl.atende.mobile.tv.ui.gui.main.activity.MainActivity)/@0x6ef11a5
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x2331faa
  mCurrentFocus=Window{ffcf7d u0 tv.go3.android.tv/pl.atende.mobile.tv.ui.gui.main.activity.MainActivity}
  mFocusedApp=AppWindowToken{e642455 token=Token{ec1030c ActivityRecord{815de3f u0 tv.go3.android.tv/pl.atende.mobile.tv.ui.gui.main.activity.MainActivity t595}}}

**Comment by PRProd** [comment]
@reinuke ~

I have just published Firemote version [v3.2.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.7) which contains the app shortcut that you requested.  Enjoy!

-Doug

**Comment by PRProd** [comment]
You're welcome!  Thanks for filling out a translation request too!

The reason I chose to name it that way is because that's the way that the [Google Play store](https://play.google.com/store/apps/details?id=tv.go3.android.tv) displays its title:

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/93dd1c12-3581-4891-b98c-8ff677460623)

I also modeled the logo for the app launch button after the one that's posted in the Play Store, even though it's a little different from what you see when you actually launch the application.

| Menu | Horizontal | Round |
| -------- | -------- | ----------|
|![image](https://github.com/PRProd/HA-Firemote/assets/25486599/09cef7bf-c141-4379-ab76-b82849aeddf4)|![image](https://github.com/PRProd/HA-Firemote/assets/25486599/ad840ed7-7926-4e16-a80b-d918f1dc50d9)| ![image](https://github.com/PRProd/HA-Firemote/assets/25486599/d38b9574-86a5-466b-a8e1-d00b8d8d45cd)|


When you find the app in the [Google Play store](https://play.google.com/store/apps/details?id=tv.go3.android.tv) does it look like the screenshot I shared, or does it look different in your region?

**Comment by reinuke** [comment]
From my computer it does show as you describe it. But it seems that we're both correct. 
There used to be apps for different countries but the merged them all. I went on a googling spree but couldn't find any articles about it. I did however stumble on this help article: https://abi.go3.tv/en/article/tv/

It shows that when you first login you have to choose from within the app your country. 
![image](https://github.com/PRProd/HA-Firemote/assets/157743108/2a3d5bd3-9cc0-4c0d-ab95-19bce628487f)

I don't use any VPN services either so I can't really check.. 
I guess it's up to you 😂

**Comment by reinuke** [comment]
When in doubt, e-mail. 
![image](https://github.com/PRProd/HA-Firemote/assets/157743108/ae97e02f-bc4d-409c-836f-b24f1c2b1632)

**Comment by PRProd** [comment]
I hope that this is true!  Let me know what they say.

**Comment by reinuke** [comment]
Meanwhile... Can confirm button works.

**Comment by reinuke** [comment]
Hey.. still no feedback from the support.. but...
for some reason the buttons don't work from the phone app... (only tried from computer last night)
Not even seeing the new buttons listed..
![Screenshot_20240308_210537_Home Assistant](https://github.com/PRProd/HA-Firemote/assets/157743108/87907587-941a-4d36-9d2e-c6d53466200c)
![Screenshot_20240308_210926_Home Assistant](https://github.com/PRProd/HA-Firemote/assets/157743108/9ae87d26-732f-49f7-9b82-3bc5bcc2e028)
![Screenshot_20240308_210936_Home Assistant](https://github.com/PRProd/HA-Firemote/assets/157743108/3021dac8-9644-4796-8b10-4d17d61d94a8)
From computer:
![20240308_211353](https://github.com/PRProd/HA-Firemote/assets/157743108/e39549c9-c766-46c1-867f-a5c2e40539f4)

Any ideas?

**Comment by PRProd** [comment]
This happens a lot!  Well, it happens enough that I wrote an article about it too.  :stuck_out_tongue_winking_eye: 

Check out this article: [Force a Refresh](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh)

**Comment by reinuke** [comment]
I feel ashamed I didn't think of this, being a sys admin..
Clearing Cache worked like a charm.

**Comment by PRProd** [comment]
I'd be happy if they added this iOS feature into the Android companion app
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/a9c5a65f-925e-4df0-8945-ed680942d6b8)

**Comment by reinuke** [comment]
Support confirmed that the app is universal across the region.
 "Go3 TV Baltics" would probably be a good fit
