### ISSUE TITLE
[New App Shortcut]: Télé Fibe (Bell Fibe TV (CA))

### ISSUE THREAD

**Issue by Drizztfire** [PRProd/HA-Firemote#337]
### App Name

Bell Fibe TV (CA)

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/ca/app/bell-t%C3%A9l%C3%A9-fibe/id724812278?l=fr-CA&platform=appleTV

### Application Details

source_list: App Store, Arcade, Balados, Réglages, TED, TV, Télé Fibe, VLC, YouTube, Émissions

### Optional Comments

This is the Bell Fibe TV (CA) app for Apple TV. The app is already there for Fire devices but the app exist for Apple TV.
In the list it's "Télé Fibe"

**Comment by PRProd** [comment]
Greetings @Drizztfire!

Thanks for your request!  While I'm helping you with this, could you help me with something?  

Judging by your request, It appears that you have set your Apple TV device to use French as the primary language.  Because of this, I would imagine that some of the built-in Firemote app shortcut buttons do not work for you right now such as settings, podcasts, etc.  As noted in the [Firemote Wiki Languages section](https://github.com/PRProd/HA-Firemote/wiki/#which-languages-are-currently-supported) this can be easily resolved,  but I will need your help with the translations.

Would you kindly [click here to help with a proper French translation](https://github.com/PRProd/HA-Firemote/issues/new?assignees=PRProd&labels=Region+Issue%2Cenhancement&projects=&template=New_Language_Support.yaml&title=%5BNew+Language+Support%5D%3A%20French&langcode=FR)?  The Firemote project will be very grateful, as well as all other users who speak French.

Thank you in advance!

-Doug

**Comment by PRProd** [comment]
Hello again @Drizztfire!

I have just published Firemote version [v3.2.7](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.7) which contains the app shortcut that you requested. Even though I'm closing this issue, it would still be awesome if you would choose to help with the [language translation](https://github.com/PRProd/HA-Firemote/issues/new?assignees=PRProd&labels=Region+Issue%2Cenhancement&projects=&template=New_Language_Support.yaml&title=%5BNew+Language+Support%5D%3A%20French&langcode=fr) too. Enjoy!

-Doug
