### ISSUE TITLE
[New App Shortcut]: App Opener

### ISSUE THREAD

**Issue by pholcroft** [PRProd/HA-Firemote#34]
### App Name

App Opener

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

To get around the issue of not being able to open side loaded apps such as TiviMate an App was created called [App Opener](https://www.aftvnews.com/customizable-buttons-on-the-fire-tv-pro-remote-cannot-open-sideloaded-apps/#:~:text=I%20have%20also,Reply) which opens another sideloaded app.

If you can add this app to the list it will allow us to open side loaded apps.

This is also a workaround for the following issue: https://github.com/PRProd/HA-Firemote/issues/32

**Comment by PRProd** [comment]
@pholcroft - Clever!

For the record, it's not that I'm unable to create shortcut buttons for side loaded apps.  The rule is there because ethically I'm personally hesitant to do this because it could encourage a user of my card to download something unsafe assuming that it was OK and vetted because it was on the list in the card.  I don't want to be responsible for a malicious app's misbehavior.  I'd rather keep that supervision in the hands of the folks who curate the official Fire TV app download list.

That being said, since the "App Opener" app IS deemed OK by the Amazon Fire TV App store right now, this shortcut will be added to the next release.  I'm waiting to hear back from some testers on some pre-release activity (#30, #31, #33) before the next official release.  Hopefully within the next 24-48 hours or so.

**Comment by PRProd** [comment]
Version [1.11.1](https://github.com/PRProd/HA-Firemote/releases/tag/v1.11.1) has been released and it contains your requested app shortcut addition.  Thank you for your testing efforts earlier, and for your patience with the timing of this release.

Thanks for your contribution!
