### ISSUE TITLE
[New App Shortcut]: SmartTube (not SmartTubeNext)

### ISSUE THREAD

**Issue by camelcamro** [PRProd/HA-Firemote#350]
### App Name

SmartTube 

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://github.com/yuliskov/SmartTube?tab=readme-ov-file#installation

### Application Details

adb_response: mSurface=Surface(name=com.liskovsoft.smarttubetv.beta/com.liskovsoft.smartyoutubetv2.tv.ui.browse.BrowseActivity)/@0x672ce0f
  mInputMethodTarget in display# 0 Window{9bb67f9 u0 com.liskovsoft.smarttubetv.beta/com.liskovsoft.smartyoutubetv2.tv.ui.browse.BrowseActivity}
hdmi_input: null
device_class: tv
entity_picture: /api/media_player_proxy/media_player.fire_tv_172_20_1_100?
friendly_name: Fire TV 172.20.1.100
supported_features: 22961

### Optional Comments

well, not sure, what is the real problem, but the existing SmartTubeNext + SmartTubeNextBeta not working for me.
but, maybe there are a different ones, which are now called: SmartTube + SmartTubeBeta and should be avialable to select ?

in any case: i have Amazon Fire TV Stick 4K Max 
thx for your help

**Comment by PRProd** [comment]
Greetings @camelcamro!

I was just looking into this since I caught [your post](https://github.com/PRProd/HA-Firemote/issues/285#issuecomment-2016910611) in discussion #285.

My initial thoughts here are as follows:
 - I think that SmartTubeNext might have been renamed to SmartTube.  All of the download links I have found, even from the website https://smarttubenext.com/ point towards the GitHub repo https://github.com/yuliskov/smarttube - I will need to look deeper into that, but I will likely change the names on the dropdown menus if this is true.
 - Based on the adb_response you posted for me, it looks like the **SmartTubeNext Beta** option *should* work assuming that you have a Firemote version newer than [v3.2.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0).  I will take a look at this soon to see why that isn't working.

**Comment by camelcamro** [comment]
thx a lot,
if i can help with any other adb debugging .... eg: logcat via adb or whatever, let me know ...

**Comment by PRProd** [comment]
@camelcamro ~

Depending on the permissions of the app and of the device, sometimes the "adbLaunchCommand" is not required and/or having it there actually causes an issue.  I suppose it is possible that in this case, not having it is the reason for the problem you are having on your device.

I just tested the Firemote launch buttons for both the [stable](https://github.com/yuliskov/SmartTubeNext/releases/download/latest/smarttube_stable.apk) and [beta](https://github.com/yuliskov/SmartTubeNext/releases/download/latest/smarttube_beta.apk) versions from https://smarttubenext.com against my [Fire TV 4-Series (2021)](https://github.com/PRProd/HA-Firemote/wiki/Smart-TV---Fire-TV-4-Series-(2021)), and they both worked as expected.  

I'm suspecting that it's something special with the device you have.  Could you clarify for me, which one do you own?  Is it the [Fire TV Stick 4K Max - 1st Gen (2021)](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-Max---1st-Gen-(2021)) or the [Fire TV Stick 4K Max - 2nd Gen (2023)](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-Max-2nd-Gen-(2023))?

**Comment by camelcamro** [comment]
having "Fire TV Stick 4K Max - 2nd Gen (2023)"
will test - the adb cmd's

then, i tested your 3 possible adb commands ...
only 1 was working ...

this one works: (tested only on: "Fire TV Stick 4K Max - 2nd Gen (2023)")

adb shell am start com.liskovsoft.smarttubetv.beta

**Comment by PRProd** [comment]
> then, i tested your 3 possible adb commands ...
only 1 was working ...
>
> this one works: (tested only on: "Fire TV Stick 4K Max - 2nd Gen (2023)")

:tada: YAY!  I'm glad we found a command that works in my environment AND yours!  :tada: 

<br>

> FYI: i also tested to call wiht "-n" start option, then it was not working !! like that is NOT OK:
adb shell am -n start com.liskovsoft.smarttubetv.beta

I agree!  That is very unusual! :man_shrugging: 

<br>

> thx - amazing support !!!!!!!!!!!!!!!!!!!!!!!!!! - cu camel

You're very welcome!  Feel free to ask any other questions, or make any other requests that you might have!  I will do my best to respond to them.  

\<rant> I can sort of understand why it's hard to get support, especially from volunteers who offer their time and efforts for free... I think It's because it takes additional time and effort.  However, I've never understood why some volunteers or users in forums choose to be rude or knowingly make unhelpful comments.  I don't wish to be in either of those categories. \</rant>


I will put this ADB command in the next Firemote release, and comment back here when it's available.

**Comment by PRProd** [comment]
@camelcamro,

Firemote version [v3.3.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.3.0) has just been released!  I'm hoping that this fixes the unusual behavior for everyone... if not, hopefully someone will let me know!  Enjoy!

-Doug

**Comment by crackn** [comment]
SmartTube Stable and Beta launchers use outdated package names

The built-in SmartTube launcher entries appear to use outdated package names.

Current SmartTube packages are:

SmartTube Stable
org.smarttube.stable

SmartTube Beta
org.smarttube.beta

On Amazon Fire TV, the Beta launcher was confirmed working with:

adb shell am start -n org.smarttube.beta/com.liskovsoft.smartyoutubetv2.tv.ui.main.SplashActivity

The same SplashActivity should also be checked for the Stable package:

adb shell am start -n org.smarttube.stable/com.liskovsoft.smartyoutubetv2.tv.ui.main.SplashActivity

Suggested launcher definitions:

"smart-tube-next": {
    "friendlyName": "SmartTube",
    "className": "smartTubeNextButton",
    "appName": "org.smarttube.stable",
    "androidName": "org.smarttube.stable",
    "adbLaunchCommand": "adb shell am start -n org.smarttube.stable/com.liskovsoft.smartyoutubetv2.tv.ui.main.SplashActivity",
    "deviceFamily": ["amazon-fire", "chromecast", "homatics", "nvidia-shield", "onn", "xiaomi"],
},

"smart-tube-next-beta": {
    "friendlyName": "SmartTube Beta",
    "className": "smartTubeNextButton",
    "appName": "org.smarttube.beta",
    "androidName": "org.smarttube.beta",
    "adbLaunchCommand": "adb shell am start -n org.smarttube.beta/com.liskovsoft.smartyoutubetv2.tv.ui.main.SplashActivity",
    "deviceFamily": ["amazon-fire", "chromecast", "homatics", "nvidia-shield", "onn", "xiaomi"],
},

I tested the Beta package/activity through Home Assistant androidtv.adb_command on a Fire TV and it launches correctly.

The current HA-Firemote Beta entry using:

com.liskovsoft.smarttubetv.beta

no longer launches the current SmartTube Beta build.

It would be useful to update both Stable and Beta launcher definitions so the built-in Firemote buttons continue to work after HACS updates.
