### ISSUE TITLE
Apple TV Buttons not working

### ISSUE THREAD

**Issue by sayam93** [PRProd/HA-Firemote#362]
### Describe the bug

The control center button works just like the home button and doesn't toggle the control center panel. I've tried tapping it as well tap & hold but it doesn't open the control center.

I believe it has something to do with #[105764](https://github.com/home-assistant/core/pull/105764)

Am I missing something?

### To Reproduce

Tapping control center button.

### Expected Behavior

The button should function.

### Which Type of Device Do You Own?

Apple TV 4K Gen 3

### Additional context

```
type: custom:firemote-card
entity: media_player.tv
device_family: apple-tv
device_type: appletv-4k-gen3
compatibility_mode: default
apple_tv_remote_entity: remote.tv
scale: '64'
defaultRemoteStyle_override: ''
app_launch_1: netflix
app_launch_2: prime-video
app_launch_3: apple-tv
visible_name_text: Bedroom
name_position: hidden
app_launch_6: function-app-switch
app_launch_7: function-search
app_launch_8: function-control-center
app_launch_4: youtube
app_launch_5: plex

```

**Comment by PRProd** [comment]
Greetings @sayam93!

It's great to have you here!

I looked over your edits to this issue, and I smiled.  :smile:  I'm hoping that it was the Firemote documentation that helped you out, and that you didn't just give up.  :smile: 

> I believe it has something to do with #https://github.com/home-assistant/core/pull/105764
>
>Am I missing something?

Nope!  You're not missing anything!  You are correct.  This issue is upstream of Firemote, so there is nothing in the Firemote code that it causing it, nor is there anything in the Firemote code that can fix it.

As you were reviewing the documentation, you may have run across this section in the [Firemote Wiki](https://github.com/PRProd/HA-Firemote/wiki) called [How Does Firemote Send commands to my devices?](https://github.com/PRProd/HA-Firemote/wiki#how-does-firemote-send-commands-to-my-devices) which explains the setup a little more thoroughly.  Firemote is just a "pretty face" that sends commands to Home Assistant integrations, just like you could do yourself through scripts.  I just get the leg work for you

```mermaid
flowchart LR
  A[/Media Player Device\]
  subgraph HA[Home Assistant]
    direction LR
    subgraph Ints[Integrations]
      direction LR
      ADB[Android Debug Bridge]
      ATR[Android TV Remote]
      intETC[etc...]
    end
    core[(core)]
    subgraph cards[Cards]
      direction TB
      FiremoteCard[[Firemote Card]] 
      cardetc[[etc...]]
    end
  end
  Ints <--> core
  core <--> cards
  A <--> ADB
  A <-.-> ATR
  ATR ~~~ cardetc
  cards <--> UI(Home Assistant Dashboard)
```

I hope this helps!

-Doug
