### ISSUE TITLE
Button to entity

### ISSUE THREAD

**Issue by Don87** [PRProd/HA-Firemote#365]
### Feature Request

The e.g. Netflix button or another button is no longer displayed as an entity in HA

**Comment by PRProd** [comment]
Greetings @Don87 

Apologies, I don't understand what you are asking for.  Could you provide more detail?

**Comment by Don87** [comment]
Hello PRProd
In a previous version there was the option to use the custom button (for example Neflix) for automation. Something like press the Neflix button and turn off or dim the light. firemote card has stored a Neflix entity  in ha, that is no longer the case. I hope you understand me?!

**Comment by PRProd** [comment]
@Don87,

The way you have described it, I'm guessing that either you've confused Firemote with something else, or maybe you are a little unclear about how Firemote functions.  Firemote DOES have options to change what a button can do, including adding commands which *could* result in creating a button that dims the lights and launches an application on your media device.  That ability has not been taken away.  However, Firemote has never had the ability to add entities to your Home Assistant system.  Let's get into that first:

It's important to have a basic understanding of [how Firemote sends commands to your media devices](https://github.com/PRProd/HA-Firemote/wiki#how-does-firemote-send-commands-to-my-devices).  Firemote is not an integration, it is just a lovelace card.  This card depends on Home Assistant integrations to bridge the gap between your dashboard and your playout devices.
```mermaid
flowchart LR
  A[/Media Player Device\]
  subgraph HA[Home Assistant]
    direction LR
    subgraph Ints[Integrations]
      direction LR
      ADB[Android Debug Bridge]
      ATR[Android TV Remote]
      intETC[etc...]
    end
    core[(core)]
    subgraph cards[Cards]
      direction TB
      FiremoteCard[[Firemote Card]] 
      cardetc[[etc...]]
    end
  end
  Ints <--> core
  core <--> cards
  A <--> ADB
  A <-.-> ATR
  ATR ~~~ cardetc
  cards <--> UI(Home Assistant Dashboard)
```
Since Firemote is not an integration it cannot create entities, it is simply a nice looking surface with buttons.
<br>

To answer your first question, there are two main documented ways to add to the default abilities of Firemote:
1. [Launcher Button Customizations](https://github.com/PRProd/HA-Firemote?tab=readme-ov-file#launcher-button-customizations)
2. [Button Overrides](https://github.com/PRProd/HA-Firemote?tab=readme-ov-file#button-overrides)
I recommend clicking on each of these links and reading the documentation.

Please let me know if you need any additional help with this, and I'll be happy to help you!  Enjoy!

-Doug
