### ISSUE TITLE
[New App Shortcut]: Oqee by Free France

### ISSUE THREAD

**Issue by Sonic62** [PRProd/HA-Firemote#39]
### App Name

Oqee Free France 

### Can this app be freely downloaded through official means?

- [X] Yes

### Optional Comments

Good morning

Would it be possible to integrate, oqee of internet provider Free France ...

Namely no official version is planned for the moment for the fire stick.

But a version that installs and works very well can be found here
https://www.lesalexiens.fr/actualites/comment-installer-oqee-sur-fire-tv-stick-ou-cube/

Link for dl compatible version is latest

https://www.lesalexiens.fr/oqeeshow

for version of
Version Android TV pour Fire OS 7+ (merci à [nic020](https://www.dealabs.com/discussions/application-apk-oqee-by-free-en-telechargement-2147104?page=11#comments)) :

Version 1.8.1 (dernière) : [lesalexiens.fr/oqeeshow](https://www.lesalexiens.fr/oqeeshow)
Thanks

**Comment by PRProd** [comment]
@Sonic62 - Hello!  Thanks for reaching out!  Unfortunately, I'm going to have to deny this request due to [policy](https://github.com/PRProd/HA-Firemote#i-want-to-have-a-shortcut-button-for-an-app-i-use-frequently-but-its-not-on-the-list--can-it-be-added) and personal liability concerns.  

I expounded on this in the request form you filled out:
  `If the app is not available to download through the native Fire TV app search feature, then it is potentially unsafe and will not be considered for app shortcuts. All "sideloaded" app requests will be rejected.` 

Even though I will be closing this request without working on it, you might find some success reading through the notes of [Issue #34](https://github.com/PRProd/HA-Firemote/issues/34) which could provide a suitable workaround for you.

I am more than happy to fulfill any other app shortcut request you may have, as long as it's available directly through the Amazon Fire TV App Search feature.  Thanks!

**Comment by PRProd** [comment]
@Sonic62 - [A new beta version](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0-beta3) is available for testing, which also happens to include this previously closed request.  

If you'd like to test it out as a beta tester, feel free to join us over at discussion #47.  We'd love to have you!

**Comment by PRProd** [comment]
This functionality exists now in the  [newest release: v2.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0)  

Enjoy!

Join the discussion #52
