### ISSUE TITLE
[Feature Request]:  Design your own remote

### ISSUE THREAD

**Issue by spuggy1968** [PRProd/HA-Firemote#404]
### Feature Request

I know you have the Other Remote options, is there any way for the DIY people to design our own remotes with PNG images, or is this something that can only be done from within your programming?   Guess wondering if there is a way to map the custom remote image of a remote to the button's within your programming.

Thanks, wonderful work!

**Comment by PRProd** [comment]
@spuggy1968 ~

Issue #404 - Feature not found.  :smile: 

Thank you for your kind words of encouragement!  

Your second guess is correct - The Firemote cards are all drawn with HTML and CSS.  The only image files used are SVGs for the app launcher logos.  This was a deliberate choice for several reasons:
<br>

## Flexibility
When the Firemote is drawn on the fly inside your dashboard as opposed to an image being displayed, it opens up possibilities that a static image would not allow.  For instance, some Firemote designs will actually shrink or grow depending on how many app launcher icons are present, which wouldn't be possible with a static background.
<br>

## Crisp Scaling
A png (or any web compatible image format other than SVG) will always look good at it's native size, but once you try to scale it up it will become blurry.  Conversely, scaling down an image will cause the (not as important) issue of using a very large file to render something that could have been created with much less bandwidth (ie: a smaller image file).  Not only do HTML/CSS rendered containers with SVG images scale perfectly while maintaining sharpness, when done right they usually are a smaller file size too.  The ability for Firemote to scale is very important for those who are making pixel perfect dashboard designs.
<br>

## Visual effects
While this could likely be done to some extent using other HACS tools, I've invested a lot of time into trying to make the buttons react to certain events in a visually appealing way.  For instance, when you click on any Firemote button, you will see it move, change colors, light up, etc.  If you look at the onn. remote, you will even notice that every button press causes a green light to blink at the top, just like the physical one does.  This detail would be more difficult to accomplish without the full control of the container & background that HTML/CSS/SVG rendering gives us.
<br>

## It Just Works
I endeavor to make each Firemote design work as best as it possibly can with very little or no user configuration.  I try to guard this project as best I can from accidental user confusion / misconfiguration so that Firemote can retain the reputation of integrity that it has built up until now.  I'm not saying that I'm opposed to big changes in the future, but I am very careful about what I choose to do and what I choose not to do.
<br>
<br>

Right now, Firemote does not allow for custom image / remote backgrounds, and there are no plans to allow for that in the near future.  If you are hoping to create your own layout using native Home Assistant buttons that accomplish "Firemote" style tasks, I can help you with the commands and/or point out where you can get them from my code or the wiki documentation.

I hope this helps!

-Doug
