### ISSUE TITLE
Sportsnet launcher not working

### ISSUE THREAD

**Issue by darbuthnot** [PRProd/HA-Firemote#407]
### Describe the bug

Hi Doug and team, love the card and it works great for apps like Netflix, Fibe, Prime etc but the Sportsnet button doesn’t do anything on my remote.  I’m happy to help troubleshoot if you like.

### To Reproduce

Added Sportsnet launcher button to card.

### Expected Behavior

Pressing button does not launch the Sportsnet app.  

### Which Type of Device Do You Own?

Fire TV Stick 4K
Fire OS 6.7.0.3 (NS6703/5183)

**Comment by PRProd** [comment]
Greetings @darbuthnot!

Thanks for letting me know about this!  As you might already know, there are [over 215 apps and functions](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers) that Firemote can handle, so the only way I can really keep each and every one of them working properly is by receiving reports like yours.  So, THANK YOU!

With that being said, I am going to need some help from you, if you can.  When this was first added (issue #352) the launcher command was working.  At that time, although I was not able to install this through the [Google play store](https://play.google.com/store/apps/details?id=com.rogers.sportsnet.sportsnet&hl=en) in my region, I was able to download / sideload the .apk file and install it to make sure it worked properly.

Today, the Google Play Store regional block is still in effect:
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/cd534ba9-7d96-4224-b6fd-6d438fd67d60)

and it looks like the most recent update for this app was posted on...
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/3dd050c7-c596-4912-873b-611f42e44017)


Today, I have not been able to find an updated .apk to download and test as I did the first time.  [APK Mirror](https://www.apkmirror.com/apk/rogers-digital-media/sportsnet-android-tv/sportsnet-android-tv-5-1-15-release/sportsnet-android-tv-5-1-15-2-android-apk-download/) has one that works, but it was from March 13, 2024.  I tried that one again, and the current Firemote button works.  No help there.  The only other versions I could find were from [APK Combo](https://apkcombo.com/sportsnet/com.rogers.sportsnet.sportsnet/) (Apr 30, 2024) and [APK Pure](https://apkpure.com/sportsnet/com.rogers.sportsnet.sportsnet) (May 6, 2024) but unfortunately those options are designed for mobile platforms, not Android or Fire TV.

So, now I need your help.  Can I ask you to [follow the procedure outlined in this linked article](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices) and post your results here?  They will likely look similar to this, but with a slight difference:
```
adb_response: mSurface=Surface(name=)
mSurface=Surface(name=com.rogers.sportsnet.sportsnet/com.rogers.sportsnet.tv.ui.AppActivity)
mSurface=Surface(name=com.android.systemui.ImageWallpaper)
mCurrentFocus=Window{858740b u0 com.rogers.sportsnet.sportsnet/com.rogers.sportsnet.tv.ui.AppActivity}
mFocusedApp=AppWindowToken{2f794ae token=Token{a212ffe ActivityRecord{52bbfb9 u0 com.rogers.sportsnet.sportsnet/com.rogers.sportsnet.tv.ui.AppActivity t5135}}}
```

Thanks again for your report, and your willingness to troubleshoot!

-Doug

**Comment by darbuthnot** [comment]
np Doug....here you go:

adb_response: mSurface=Surface(name=com.rogers.sportsnet.tv.firetv/com.rogers.sportsnet.tv.ui.AppActivity)
  mCurrentFocus=Window{e0711b u0 com.rogers.sportsnet.tv.firetv/com.rogers.sportsnet.tv.ui.AppActivity}
  mFocusedApp=AppWindowToken{2420858 token=Token{a25e3ca ActivityRecord{e7ef335 u0 com.rogers.sportsnet.tv.firetv/com.rogers.sportsnet.tv.ui.AppActivity t4165}}}
hdmi_input: null
device_class: tv
friendly_name: Fire TV 10.55.107.57
supported_features: 22961
source_list: com.amazon.tv.ime, com.amazon.imp, com.amazon.tv.alexaalerts, android.ext.services, com.amazon.device.messaging, com.android.proxyhandler, com.amazon.client.metrics, com.amazon.vizzini, com.amazon.tcomm, com.amazon.tv.devicecontrol, com.amazon.whad, com.amazon.tv.launcher, com.amazon.dialservice, com.amazon.kso.blackbird, logcat, com.amazon.whisperjoin.middleware.np, com.amazon.whisperjoin.wss.wifiprovisioner, com.amazon.connectivitycontroller, com.amazon.device.rdmapplication, Netflix, ca.bell.tv.firetv, com.amazon.webview.chromium:AWVMetricsProcess, com.amazon.ftv.xpicker, com.amazon.whisperlink.core.android, com.amazon.uxcontrollerservice, com.amazon.alexa.externalmediaplayer.fireos, com.android.statementservice, com.amazon.ceviche, com.amazon.diode, com.amazon.device.blepa, com.amazon.prism.android.service:remote, com.amazon.bueller.photos, com.amazon.device.bluetoothkeymaplib, com.amazon.tv.devicecontrolsettings, com.amazon.perfc, com.amazon.aca, com.amazon.wirelessmetrics.service, Amazon Video, com.amazon.tv.notificationcenter, Prime Video (FireTV), FireTV Store, com.amazon.tv.settings.v2, com.amazon.storage.manager, com.android.providers.downloads, com.rogers.sportsnet.tv.firetv
app_id: com.rogers.sportsnet.tv.firetv
source: com.rogers.sportsnet.tv.firetv
entity_picture: /api/media_player_proxy/media_player.fire_tv_10_55_107_57?token=b05c47c0c9147627e0085ac5630712671ef6282d5d4c46017d686de6cd1f645d&cache=f46260872626eb5a

**Comment by PRProd** [comment]
Ahh!  I see what's happening here.  It looks like there is a different app specifically designed for Amazon Fire.

I want to update this correctly the first time, so if you're still willing to do some testing, I'd like for you to try this:
 1. Go to the Home Screen (or any other app) on your Fire Stick as long as it's NOT Sportsnet
 2. Follow steps 1-4 from [the instructions you used before](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices) - SKIP STEP 0
 3. Instead of using the command listed in step 5, use this instead: 
  ``adb shell am start -n com.rogers.sportsnet.tv.firetv/com.rogers.sportsnet.tv.ui.AppActivity``
 4. Click on CALL SERVICE
 
 Did Sportsnet launch on your Firestick?

**Comment by darbuthnot** [comment]
Yes…that worked! :-)

**Comment by PRProd** [comment]
Excellent!  Thank you for testing!  I've made that change in my dev environment, and it will be pushed with the next Firemote release.  I'll keep this issue open until it has been published.

**Comment by darbuthnot** [comment]
Thanks Doug…happy to help! No rush, I’ll write a script with a custom app launcher in the meantime :-)

**Comment by PRProd** [comment]
You're my favorite user today!  Find a mirror and smile at yourself for me.

**Comment by PRProd** [comment]
Good news @darbuthnot!

I have just published Firemote version [v3.4.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.3) which contains the official fix.  You can retire your script if you want to.  :smile: 

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by darbuthnot** [comment]
Hi Doug, I re-tested but I must be doing something wrong as the button is not working still.  My script still works and I did a HA restart to clear cache.  Any suggestions?

**Comment by PRProd** [comment]
@darbuthnot ~

That makes me sad... we will figure it out, though.

If you follow this link, you can see the updated amazon fire launch command was pushed in the update **May 2024 Launcher Updates 2** :  https://github.com/PRProd/HA-Firemote/blame/4ffccddb1e49518377d721bb2072d2820764c13f/dist/launcher-buttons.js#L4887-L4889

Since that [updated launcher command](https://github.com/PRProd/HA-Firemote/blame/4ffccddb1e49518377d721bb2072d2820764c13f/dist/launcher-buttons.js#L4887-L4889
) matches [the launcher command you validated](https://github.com/PRProd/HA-Firemote/issues/407#issuecomment-2105166040), I don't believe that is our issue.
```json
"amazon-fire": {
    "appName": "com.rogers.sportsnet.tv.firetv",
     "androidName": "com.rogers.sportsnet.tv.firetv",
     "adbLaunchCommand": "adb shell am start -n com.rogers.sportsnet.tv.firetv/com.rogers.sportsnet.tv.ui.AppActivity",
}
```

I have three theories:

 1. The most likely theory here is that you are still experiencing a cache issue.  Home Assistant has extremely sticky cache that somehow manages to violate the rules of caching at times.  It comes up a lot, which is why I wrote the [Force A Refresh](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) article in the Firemote wiki, and why I tend to post that link to the issue threads before closing them.  If you've followed these steps already, (which I assume you have) there is one more thing that you could try.  Through HACS, you could attempt to un-install and then re-install the HA-Firemote card.  Some have found luck with that method.

 2. My next theory has to do with your Firemote card configuration.  If your Device Family isn't set to Amazon Fire, the incorrect launcher command will fire and it will not succeed.

 3. My last theory is that perhaps there is something that wasn't quite cleaned up fully when you removed your script and override.  Perhaps taking another look at that YAML would be worthwhile?

Please let me know what you find.  I'd really like to get this working properly for you.

-Doug

**Comment by darbuthnot** [comment]
Thanks Doug....rather than uninstalling the card, I went to the HACS screen and did a "redownload" on the card.  I don't know if that's the same as un-install/re-install but it's good now. :-)

Thanks again for all your work!

**Comment by PRProd** [comment]
YAY!  Glad to hear it!

You're very welcome!
