### ISSUE TITLE
[New App Shortcut]: CANAL+

### ISSUE THREAD

**Issue by TPM-dev** [PRProd/HA-Firemote#408]
### App Name

CANAL+ App

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.canalplus.canalplus

### Application Details

adb_response: mSurface=Surface(name=)/@0x77e70ed
mSurface=Surface(name=com.canalplus.canalplus/tv.solocoo.htmlapp.FullscreenActivity)/@0xa9b276e
mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x9f6d888

### Optional Comments

supported_features: 23997
app_id: com.canalplus.canalplus
app_name: com.canalplus.canalplus
source: com.canalplus.canalplus

**Comment by PRProd** [comment]
Greetings @TPM-dev!

Since this app isn't available through the Google Play store in my region, I had to sideload it for testing.  To confirm that I've sideloaded and tested the same app that you are requesting, can you do me a quick favor?

 1. Go to the home screen on your Chromecast or open any app that isn't CANAL+
 2. Follow [the same instructions](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices) you used when making this request, but only use steps 1-4.  (skip step 0)
 3. Type or copy/paste this command instead of the one that is listed in step 5:
```adb shell am start -n com.canalplus.canalplus/app.solocoo.tv.solocoo.login.splash.SplashActivity```
 4. Click the **CALL SERVICE** button.

Did CANAL+ open on your Chromecast?

If it didn't, what happens when you try this command?
```adb shell am start -n com.canalplus.canalplus/tv.solocoo.htmlapp.FullscreenActivity```

I look forward to hearing back from you.  Thanks!

-Doug

**Comment by TPM-dev** [comment]
Hi,

Thanks for taking the time to add this, and sorry for the late reply

I've followed the steps above and on the first service call: `adb shell am start -n com.canalplus.canalplus/app.solocoo.tv.solocoo.login.splash.SplashActivity`, nothing happened.

However on that other command: `adb shell am start -n com.canalplus.canalplus/tv.solocoo.htmlapp.FullscreenActivity`, the CANAL+ app started.

I guess you're on the right track!

**Comment by PRProd** [comment]
Thanks for that info @TPM-dev!

Good news!  I have just published Firemote version [v3.4.3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.3) which contains your CANAL+ app shortcut request.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
