### ISSUE TITLE
[New App Shortcut]: Ninja Player

### ISSUE THREAD

**Issue by cybermedicuk** [PRProd/HA-Firemote#409]
### App Name

Ninja

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://teamninja.live/ninjaplayer.apk

### Application Details
device_class: tv
friendly_name: Fire TV
supported_features: 22961
adb_response: mSurface=Surface(name=com.ninja.ninjabox/com.ninja.ninjabox.view.activity.SeriesAllDataSingleActivity)/@0x7be83e0   mCurrentFocus=Window{639ac u0 com.ninja.ninjabox/com.ninja.ninjabox.view.activity.SeriesAllDataSingleActivity}   mFocusedApp=AppWindowToken{ddb9bb1 token=Token{cf08e58 ActivityRecord{7a2973b u0 com.ninja.ninjabox/.view.activity.SeriesAllDataSingleActivity t824}}}
source_list: com.ninja.ninjabox app_id: com.ninja.ninjabox 
source: com.ninja.ninjabox
entity_picture: /api/media_player_proxy/media_player.fire_tv_192_168_0_18?token=9e7f802614efd4eff10e002bdede91334b227b25731160577341a8be4a633a95&cache=47b64578d8640bc5

### Optional Comments

cyber_dread@hotmail.com if you need any more info...
Thank you

**Comment by PRProd** [comment]
@cybermedicuk ~

The [link you provided](https://teamninja.live/ninjaplayer.apk) is for an app with the android package name of **com.jlwockee.iMPlayer** which does not match your request for an app with the android name of **com.ninja.ninjabox**

Looking through the other APKs on that site ~
| Link | Package |
| ---- | ----- |
| [ninjaott.apk](https://teamninja.live/ninjaott.apk) | com.ottpluserpass.app |
| [ninjaxc.apk](https://teamninja.live/ninjaxc.apk) | com.xc.ANSpanels |
| [ninjaglobal.apk](https://teamninja.live/ninjaglobal.apk) | com.nathnetwork.xciptv |
| [ninjaflix.apk](https://teamninja.live/ninjaflix.apk) | com.magoware.dmcenter.webtv |
| [iptvsmarters.apk](https://teamninja.live/iptvsmarters.apk) | com.team.ninjaapp |
| [tivimate.apk](https://teamninja.live/tivimate.apk) | com.ninja.ottapp |
| [ninjaall.apk](https://teamninja.live/ninjaall.apk) | com.qdeluxe.app |
| [ninjavod.apk](https://teamninja.live/ninjavod.apk) | global.store |
| [ninjaplayer.apk](https://teamninja.live/ninjaplayer.apk) | com.jlwockee.iMPlayer |

All of this looks incredibly suspicious to me... but I could be wrong.

Did you give me an incorrect link, or is this something else?

**Comment by cybermedicuk** [comment]
I've been using the App via my Firestick for a while and its been fine. I then bought a Fire TV and "somehow" managed to get same app set up perfectly on that too.
From your list, its def the last one called ninjaplayer that I've been using.

Really appreciate your work, but don't spend too much time on it, especially if you feel its dodgy.
It was a just a great way to finish off my setup I've been creating.

Thanks again

Anthony

**Comment by PRProd** [comment]
@cybermedicuk ~

The chart I made was based on searching the https://teamninja.live website and coming across a download page: https://teamninja.live/installation-2/


> From your list, its def the last one called ninjaplayer that I've been using.

The items in my chart are the APKs listed there, which included the https://teamninja.live/ninjaplayer.apk that you provided in your initial request, and is the "last one called ninjaplayer" as you enumerated.

Upon re-inspecting this specific APK, my chart is still correct.  The package name does not match your request
 - [linked APK](https://teamninja.live/ninjaplayer.apk) package name: **com.jlwockee.iMPlayer**
 - Package name in [your request](https://github.com/PRProd/HA-Firemote/issues/409#issue-2290240299): **com.ninja.ninjabox**

You can inspect the package yourself using an online tool provided at https://sisik.eu/apk-tool

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/0d8fc04a-3b08-4e65-8450-01ae73484d66)


So, what does this mean?
 1. I'm unable to download the app you have installed, so that makes it impossible for me to test before releasing code
 2. You *might* be running an older version of this app, and that could be why the package names do not match.  If this is true, I cannot proceed with adding it to the Firemote base since the launcher would already be out of date, and only work for you.
 3. You might have sent me an incorrect link in your initial request

What have I looked into?
 1. I've searched for an alternative apk with the name com.ninja.ninjabox, but have been unable to find one online.
 2. I've scanned the linked apk at [virustotal.com](https://www.virustotal.com/gui/file/081fddfcc188a2e29c0dfe8a3d6f43262a3e5fa71abc5e858544a8a6326f63ee/detection) and it is showing 2 out of 66 security vendors' analysis are flagging it as potentially malicious.  These could be false positives, or they could be legit issues
 3. I tried running the linked APK on my Fire TV, and it crashes immediately
 
 What are our options now?
 If we cannot work through the discrepancies between what your Fire device is reporting for this app, and how the linked APK actually behaves, then I might not choose to move forward with adding this to Firemote.

That does NOT mean that you are out of luck, though!  Firemote allows you to create your own launcher buttons to directly call a service, or directly call a script.  Take a look at the [Create a custom button for yourself](https://github.com/PRProd/HA-Firemote/wiki#create-a-custom-button-for-yourself) article in the firemote wiki for more information.  If you choose this route, and need help completing the process, I can help you with that too, just let me know.

I hope this makes sense.  Let me know!

-Doug

**Comment by cybermedicuk** [comment]
That all does make sense, thank you.
The App came preloaded on a Firestick.

I think you have spent enough time trying to get this to work, so please accept my thanks and now move onto someone else's request.

I shall probably try a different App, that does the same thing, but a reputable one.

I shall also look into your suggestion of me creating a Custom button.
Thank you for offer of help in that one too.

Kindest regards and many thanks for trying, really appreciated.

Anthony Vickers

**Comment by PRProd** [comment]
You are welcome.  I will close this issue now.
