### ISSUE TITLE
Binge AU app shortcut not working on Amazon Fire TV Stick 4K Max

### ISSUE THREAD

**Issue by Spartan51150** [PRProd/HA-Firemote#413]
Hi it seems they must have updated the app name and as such the app shortcut no longer works.

au.com.streamotion.ctv.binge/au.com.streamotion.ctv.MainActivity

The above worked for using a home assistant service entity call.

**Comment by PRProd** [comment]
Greetings @Spartan51150!

Thank you for giving me this extremely useful information!
> au.com.streamotion.ctv.binge/au.com.streamotion.ctv.MainActivity

As I started working on this, I ran across a few things.  First, I (re)discovered that the binge app isn't available in my region for my Fire TV Stick 4K Max or any of my other Amazon Fire devices.  I also (re)discovered that it isn't available from the Google Play store in my region for any of my other Android TV devices, so it was time to go searching for an APK to download.

The original app name that was working since issue #157 (original request was made by @michael7oliver for the NVIDIA shield) was ``au.com.streamotion.ares.tv``, and I noted that you have provided a new app name of ``au.com.streamotion.ctv.binge``.  So, I began searching for an app with the name that you provided, and I was unable to locate one.  I was successful in finding a few recently updated app versions that didn't match the new app name you provided ~

 - Download link: https://www.apkmirror.com/apk/hubbl-pty-ltd/binge-for-android-tv-android-tv/binge-for-android-tv-android-tv-3-1-0-release/binge-for-android-tv-3-1-0-android-apk-download/
Upload date: **May 6, 2024**
Version: 3.1.0 (3010103)
NEW adb command: adb shell am start -n au.com.streamotion.ares.tv/au.com.streamotion.tv.SplashActivity

 - Google Play Store:
https://play.google.com/store/apps/details?id=au.com.streamotion.ares.tv

 - Download link: https://apkpure.com/binge-for-android-tv/au.com.streamotion.ares.tv
Upload date: **May 19, 2024**
Version: 3.1.0
NEW adb command: adb shell am start -n au.com.streamotion.ares.tv/au.com.streamotion.tv.SplashActivity

 - Download link: https://apkcombo.com/binge-for-android-tv/au.com.streamotion.ares.tv/


I did have success in downloading some of these APK files and running them successfully on my devices, but now we have two issues:
 1. I can't find/download the specific app you are referring to
 2. The ADB launch command for the ``au.com.streamotion.ares.tv`` *did* change, so I will likely need to make an update for that one  (I'm hoping that @michael7oliver can let me know what's happening on their NVIDIA shield)


Can you tell me the method you used to download this app to your Firestick?

-Doug

**Comment by Spartan51150** [comment]
So the app is Binge and it is available in my region just on the app store. So I just downloaded it from there 

The details I can find on it are
Version: 1.0.9
Original release date: 22 may 2023
Last updated: 22 may 2023
Developer: Hubbl Pty Limited
Size: 1.2MB


The developer used to be called streamotion

I can't seem to find an APK matching this version anywhere though. 

This thread suggests it's the one they have available intentionally I guess. Search 1.0.9 and read the couple comments.
 https://forums.whirlpool.net.au/archive/9067pxk9-3

**Comment by PRProd** [comment]
@Spartan51150 & @michael7oliver ~

I have just published Firemote version [v3.4.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.4).  I updated the Amazon Fire shortcut to use the one that @Spartan51150 provided in this issue request.  I updated the remaining Android app shortcuts to work with the newest app version available for download from many places.  If someone chooses to sideload the newest version onto an Amazon Fire device, I've added an entry called **Binge (AU) alt** that will work for them as well.

I hope that this satisfies all of the issues.  Please let me know if you disagree.

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
