### ISSUE TITLE
[New App Shortcut]: ITVX

### ISSUE THREAD

**Issue by chris-y** [PRProd/HA-Firemote#420]
### App Name

ITVX

### Device Platform

Roku

### Required Information

app_id: "42329"
app_name: ITVX
source: ITVX

**Comment by PRProd** [comment]
Greetings @chris-y!

I have just published Firemote version [v3.4.5](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.5) which contains your app shortcut request for Roku.  Since I'm unable to download and test this in my region, please let me know if you have any issues using the new button.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
