### ISSUE TITLE
Make "Visible Device Name" color white for easier viewing

### ISSUE THREAD

**Issue by richtj999** [PRProd/HA-Firemote#44]
**Is your feature request related to a problem? Please describe.**
I am having a hard time seeing the visible device name text in black on the black fire remote

**Describe the solution you'd like**
I tried to change the color from black to white in the JS file which didnt work and also tried to add text into the card

**Describe alternatives you've considered**
primary-background-color: '#FFFFFF'
secondary-background-color: '#FFFFFF'
table-row-background-color: '#FFFFFF'
table-row-alternative-background-color: '#FFFFFF'
visible_name_text: Den
primary-text-color: '#FFFFFF'
secondary-text-color: '#FFFFFF'

**Additional context**
I didnt get an error from the above but it didnt work either (the text color change).

The card is great!  Love it!  

I was using something else and the only nice thing i could do with it that I am struggling with on your card is pointing the volume controls to the TV direct 

Similar to:
volume_down:
  service: media_player.volume_down
  data:
    entity_id: media_player.maindensam
volume_up: null
service: media_player.volume_up
data: {}
target:
  entity_id: media_player.maindensam
volume_mute:
  service: media_player.volume_mute
  service_data:
    command: volume_mute
    entity_id: media_player.maindensam

**Comment by PRProd** [comment]
@richtj999 -  As of right now, there isn't a mechanism for you to choose your own color for the device label.  I'm going to keep this issue open until I'm able to provide something for you.

- - - - 

In regards to this:
> I was using something else and the only nice thing i could do with it that I am struggling with on your card is pointing the volume controls to the TV direct

There **is** a way to do this with the Firemote card right now.  Full instructions can be found in the [README.md](https://github.com/PRProd/HA-Firemote/blob/main/README.md) file under the [Button Overrides ](https://github.com/PRProd/HA-Firemote#button-overrides) heading.  There was a discussion in the past ( #6 ) about adding this functionality in a way similar to what you were trying to do, but I have not built that yet since the script feature has been a reasonable workaround in the meantime.

**Comment by PRProd** [comment]
This new functionality has been added in the recent pre-release version(s).  I will keep this open until the official release.

**Comment by PRProd** [comment]
This functionality exists now in the  [newest release: v2.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0)  

Enjoy!

Join the discussion #52
