### ISSUE TITLE
Randomly will turn on tv

### ISSUE THREAD

**Issue by Nash738850** [PRProd/HA-Firemote#441]
### Describe the bug

The roku tv will randomly turn on.

### To Reproduce

I do not know as our tv is off.

### Expected Behavior

don't turn on the tv

### Which Type of Device Do You Own?

TCL roku tv

### Troubleshooting Steps Completed

![IMG_2486](https://github.com/PRProd/HA-Firemote/assets/86806703/62602192-5ee0-4d9a-8e9e-21fdaf6294de)

**Comment by PRProd** [comment]
@Nash738850 ~

Firemote cannot cause this behavior.  It is not an integration, it is simply a card that uses built-in Home Assistant integrations.  ([More information can be found here](https://github.com/PRProd/HA-Firemote/wiki#how-does-firemote-send-commands-to-my-devices))  Only integrations can send commands directly and/or misbehave in this way.  Firemote cannot do this without user input from the dashboard.

I hope this helps.

-Doug

**Comment by Nash738850** [comment]
It does. We were both watching videos on our phone and nothing else was. Why did the log show that then? That’s where I’m confused as there was no user input. Sent from my iPhoneOn Jun 10, 2024, at 5:51 PM, Doug Nelson ***@***.***> wrote:﻿
Closed #441 as not planned.

**Comment by PRProd** [comment]
@Nash738850 ~

Ahh... I think I see where the confusion is coming from.  Because you have your Roku TV connected to Home Assistant through the Roku integration, your log should ALWAYS show a record of when the TV turns on or off.

Try this:  Watch the logfile on your phone or computer while pressing the power button on your TV's physical remote control.  What you should notice is that Home Assistant logs the power turning on and off even when it wasn't the thing that commanded the power to turn on or off.

With that understood, there is one common reason why TVs might seem to power themselves on or off without you directly asking it to, and that is [CEC](https://support.roku.com/article/360034303013).  If you have any CEC enabled device connected to your TV via HDMI, it could be the thing that's commanding your TV to turn on.  If this behavior becomes a frustration, you may opt to turn off CEC on your TV.

**Comment by Nash738850** [comment]
Hello,How can I open a new ticket? I am wondering if you can add the private listening?Sent from my iPhoneOn Jun 10, 2024, at 6:47 PM, Christian Hatch ***@***.***> wrote:﻿It does. We were both watching videos on our phone and nothing else was. Why did the log show that then? That’s where I’m confused as there was no user input. Sent from my iPhoneOn Jun 10, 2024, at 5:51 PM, Doug Nelson ***@***.***> wrote:﻿
Closed #441 as not planned.
