### ISSUE TITLE
[New App Shortcut]: Kodi

### ISSUE THREAD

**Issue by shane-wakefield** [PRProd/HA-Firemote#45]
### App Name

Kodi

### Can this app be freely downloaded through official means?

- [X] Yes

**Comment by PRProd** [comment]
@shane-wakefield - Do you have Kodi installed on an Amazon Fire device?  If so, did you sideload it?  I'm unable to find it in the Amazon Fire App Store, but I do see it in the Google Play store through my NVIDIA shield device.

I'm asking out of curiosity because I'm currently in the process of adding NVIDIA Shield functionality into the Firemote project, and I'd like to be careful about the app shortcuts listed as available for each distinct platform.  If you're not using an Amazon Fire device, what kind of device are you using?  Would you be willing to [cast your vote in the poll here](https://github.com/PRProd/HA-Firemote/discussions/41)?

**Comment by alaindaix13** [comment]
Hello @shane-wakefield,
I would also like to have Kodi as a shortcut to use it on an Android TV (Freebox Pop). I also use Kodi on my FireStick, but it is necessary to download the application via the Downloader application at https://kodi.tv/download. Here's a small tutorial in French: https://www.lesalexiens.fr/actualites/installer-kodi-sur-amazon-fire-tv-stick-cube/.
Similarly, if it is possible to integrate the SmartTube application (https://smartyoutubetv.github.io/) in the same way :-)

**Comment by PRProd** [comment]
@shane-wakefield - This new functionality has been added in the recent [pre-release](https://github.com/PRProd/HA-Firemote/releases) version(s) of Firemote.  I will keep this issue open until the pre-release becomes an official release.  You are more than welcome to take the beta version for a spin, and [join the conversation here](https://github.com/PRProd/HA-Firemote/discussions/47).

@alaindaix13 - If you want to test the beta version, and you get a chance before @shane-wakefield, could you let me know how the Kodi app works on the Firestick?  I haven't sideloaded it to test it out.  The SmartTube app request was just opened by another user as a part of issue #48.  You might want to follow that one for updates.  For any future app shortcut requests, I welcome you to [open a new issue](https://github.com/PRProd/HA-Firemote/issues/new/choose) and follow the detailed instructions there. 

Thanks!

**Comment by alaindaix13** [comment]
Hello @PRProd , I tested the beta version, and I'm able to launch Kodi on the Freebox Pop. Thank you

**Comment by PRProd** [comment]
This functionality exists now in the  [newest release: v2.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0)  

Enjoy!

Join the discussion #52
