### ISSUE TITLE
[New App Shortcut]: TV2 Play

### ISSUE THREAD

**Issue by SumMarius** [PRProd/HA-Firemote#452]
### App Name

TV2 Play

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=no.tv2.sumo&hl=no

### Required Information

See comments

### Optional Comments

This is a Phillips Android TV, so it's not behaving the same way.
app_id: no.tv2.sumo}
app_name: no.tv2.sumo}
source: no.tv2.sumo}
entity_picture: >-
  /api/media_player_proxy/media_player.android_tv_10_10_11_233?token=48cee7c37135fa28a4daf5ea9cd395db38f4d4ffbc09ac60af6dd35e3501c3df&cache=01b2110c90bfb069

**Comment by PRProd** [comment]
Greetings @SumMarius!

Unfortunately, I have to deny this request for now since the Phillips Android TV is not officially supported by Firemote.

If you are interested in official support for the Phillips Android TV, please cast your vote in the poll [Vote for what gets added next!](https://github.com/PRProd/HA-Firemote/discussions/41) to help steer this project.

In the meantime, I suggest taking a look at the Firemote Wiki section titled [Create a Custom Button for Yourself](https://github.com/PRProd/HA-Firemote/wiki#create-a-custom-button-for-yourself) which can help guide you through the process of making your own App Shortcut Button.  If you end up getting stuck I can try to help you, but since I don't own a Phillips Android TV I can't offer any guarantees.

I hope this helps.

-Doug
