### ISSUE TITLE
Philo shortcut not working

### ISSUE THREAD

**Issue by Dante2202** [PRProd/HA-Firemote#458]
### Describe the bug

I am trying to use philo on my 2019 shield pro but it does not work. Youtube, netflix, plex all work but philo does nothing.

### To Reproduce

Add philo to the Firemote Card configuration, I test it by pressing the philo button but it does not do anything.

### Expected Behavior

Philo to launch but it does not.

### Which Type of Device Do You Own?

Nvidia Shield Pro 2019

**Comment by PRProd** [comment]
Greetings @Dante2202!

THANK YOU for letting me know about this!  This kind of thing happens from time to time when an app's author makes changes or updates to the app's code.  Since Firemote supports over 215+ apps (most of which I don't use myself) I don't typically catch these changes until someone brings them to my attention.  Thank you.

I have just published Firemote version [v3.4.10](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.10) which contains the updated commands that fix this issue.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
