### ISSUE TITLE
[New App Shortcut]: HBO Max (North America)

### ISSUE THREAD

**Issue by SheffS4** [PRProd/HA-Firemote#464]
### App Name

HBO Max

### Device Platform

Amazon Fire

### Required Information

source_list: HBO Max
app_id: com.hbo.hbonow
source: HBO Max
adb_response: mSurface=Surface(name=com.hbo.hbonow/com.wbd.beam.BeamActivity)/@0xd9e41bb
  mCurrentFocus=Window{e3f46a u0 com.hbo.hbonow/com.wbd.beam.BeamActivity}
  mFocusedApp=AppWindowToken{8af454d token=Token{8e0ace4 ActivityRecord{4952877 u0 com.hbo.hbonow/com.wbd.beam.BeamActivity t4477}}}
hdmi_input: null
device_class: tv
entity_picture: /api/media_player_proxy/media_player.fire_tv?token=4ecd74a9eca1f9f5b88cbf3b1de7ae78f6f8db9e06eb06e49b08a6f379511cad&cache=45d6cb9ef1d06b0f
friendly_name: Fire TV
supported_features: 22961

**Comment by PRProd** [comment]
Greetings @SheffS4!

Good news!  The shortcut app launcher button for this app already exists.

About 14 months ago, HBO changed the name of their app from **HBO Max** to just **Max**.  If you have Firemote version [v3.0.4](https://github.com/PRProd/HA-Firemote/releases/tag/v3.0.4) (released on November 3 2023) or newer, simply select **Max** from the list.

![image](https://github.com/user-attachments/assets/bcdff4a6-2122-4c31-b75b-9a0a9eea238b)

I understand the potential confusion since **Max** isn't the most intuitive name, and because the Firemote app list also contains an item called **HBO Max - Denmark/Netherlands**.  There's actually some interesting history behind that, which you can read about in [issue #274](https://github.com/PRProd/HA-Firemote/issues/274).  In that issue's discussion thread, Github user @dennisholtkamp posted [this message](https://github.com/PRProd/HA-Firemote/issues/274#issuecomment-1990988100):
> There is a public broadcasting company called Max in the Netherlands that prevents HBO Max to br renamed for legal reason

Since this app launch button already exists, I'll be closing this issue for now.  Feel free to continue the conversation here, or re-open the issue if you have a related concern that I did not address.

I hope this helps!

-Doug
