### ISSUE TITLE
[New App Shortcut]: Orange TV (FR)

### ISSUE THREAD

**Issue by Swiiney** [PRProd/HA-Firemote#465]
### App Name

Orange TV

### Device Platform

Amazon Fire, Chromecast, NVIDIA Shield, Xiaomi

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.orange.owtv.tv

### Required Information

mSurface=Surface(name=com.orange.owtv.tv/com.orange.otvp.SplashScreen)/@0x732059
mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x84ed5d1

**Comment by PRProd** [comment]
Greetings @Swiiney!

I have just published Firemote version [v3.4.11](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.11) which contains your app shortcut request.  Since Orange TV is not available for download in my region, I was unable to test it.  Please let me know if you experience any issues with the new button.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by Swiiney** [comment]
Thank you for the update.
Button is working

Regards

**Comment by nachodomotica** [comment]
Hola, soy muy novato y necesito ayuda. Estoy encantado con firemote pero me falta poder usar el botón de Orange. Mi problema es que mi Orange no es de Francia, sino de España. Hay alguna solución??

Muchas muchas gracias!
