### ISSUE TITLE
[New App Shortcut]: HBO Max (The Netherlands)

### ISSUE THREAD

**Issue by darkrain-nl** [PRProd/HA-Firemote#466]
### App Name

HBO Max (The Netherlands)

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.wbd.hbomax

### Required Information

adb_response: |-
  mSurface=Surface(name=com.wbd.hbomax/com.wbd.beam.BeamActivity)/@0xa9814bd
        mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x40e9d80

### Optional Comments

Yep they changed the app in The Netherlands, the old purple one might still work, but they want us to use the new blue one.
Also this replace the Eurosport Player that will be discontinued (or maybe already is)...

**Comment by PRProd** [comment]
Thanks @darkrain-nl!

Since I'm unable to test these changes in my region (US) I want to be absolutely sure that I'm understanding everything correctly, and that I publish working updates the first time instead of breaking stuff.  I'm sure you can appreciate that.  😄
<br>

## Logo Question
Based on the [Google Play Store link](https://play.google.com/store/apps/details?id=com.wbd.hbomax) you provided, I've come to this conclusion but I want to confirm with you that this is correct:

| Current Firemote Logo | What Firemote should been using | Updated Logo (this request) |
| --------------------  | ----------------------------- | ---------------- |
| ![image](https://github.com/user-attachments/assets/61b0e86e-e8b6-497e-9921-1ac86905cc8c) | ![image](https://github.com/user-attachments/assets/efbcccb5-e4a6-4cf3-a9f3-6ef964049c3d) | ![image](https://github.com/user-attachments/assets/e536fb3a-9207-45a4-a56e-5a51a8629674) |
<br>

## New App Launcher
In addition to that question, I also want to know if the new app launcher command I want to use will work for you.  I have no way of testing it myself, so I'm counting on you for this.  You've done it before, so I'm not worried. 😉 

The testing procedure will be similar to the one you used when [gathering the required information for your shortcut request](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices) but abbreviated and with a few modifications.
 1. IMPORTANT: Open the **HOME SCREEN** on your device FIRST and leave it open.
 2. In Home Assistant, Open Developer tools
 3. Click the SERVICES Tab
 4. In the Service menu, select Android Debug Bridge: ADB command
 5. Select your device by clicking on the + Choose Entity button in the Targets section
 6. Type or copy/paste ``adb shell am start -n com.wbd.hbomax/com.wbd.beam.BeamActivity`` into the command field
 7. Click the CALL SERVICE button

If everything works as expected, you should see the new (blue) updated version of HBO Max open on your Chromecast when you click the CALL SERVICE button. Please let me know if this was successful or not.
<br>

## Eurosport Player
I just want to double confirm here that the [Eurosport Player app from #391](https://github.com/PRProd/HA-Firemote/issues/391) you initially requested can be removed from Firemote, is that correct?
<br>

Thanks for your help!  I truly appreciate it!

-Doug

**Comment by darkrain-nl** [comment]
Hi Doug,

Logo, correct the "Updated Logo (this request)" is the one.

New app launcher, the command works and opens the app.

Eurosport Player, well got an email it will be stopped on 22 July 2024, so yes can be removed.

Thanks :-)

regards, darkrain

**Comment by PRProd** [comment]
@darkrain-nl ~

PERFECT!  Thanks!

-Doug

**Comment by PRProd** [comment]
@darkrain-nl ~

I have just published Firemote version [v3.4.12](https://github.com/PRProd/HA-Firemote/releases/tag/v3.4.12) which contains these updates.  Thanks for making communication easy!  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by darkrain-nl** [comment]
Thanks, works like charm.
