### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by tanderson1973** [PRProd/HA-Firemote#468]
### Is your feature request related to a problem?

No

### Feature Request

Is there the ability to rename the buttons on JVC card, HA-Firemote, for example "SUBT", "LIVE" and "GUIDE" etc. Ive tried button override using name, Label or visible_name_text and not having any joy. I have created scripts to call other commands but cant see how to change button name

Many thanks

**Comment by PRProd** [comment]
Greetings @tanderson1973!

To answer your question, no.  There isn't currently a way to do what you are asking.  Not too long ago, user @manonstreet requested a feature very similar to this in issue #295 but in reference to button images instead of text.

Since your request is nearly identical to #295, I'm going to close this one as "duplicate" and recommend that you check over there for updates on this topic.

Thanks for your suggestion!

-Doug
