### ISSUE TITLE
[New App Shortcut]: coupang Play

### ISSUE THREAD

**Issue by ddarkchu** [PRProd/HA-Firemote#510]
### App Name

coupang Play

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=com.coupang.mobile.play&hl=en

### Required Information

adb_response: mSurface=Surface(name=com.coupang.mobile.play/com.coupang.play.features.main.MainActivity)/@0xcdce911
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x5ce9513

**Comment by PRProd** [comment]
Greetings @ddarkchu!

I have just published Firemote version [v4.0.5](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.5) which contains your app shortcut request for **coupang play**.  I am not able to fully test this new button because this app is not officially available in my region, so please let me know if you have any issues.  Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.
