### ISSUE TITLE
[Feature Request]: private listening 

### ISSUE THREAD

**Issue by Nash738850** [PRProd/HA-Firemote#511]
### Is your feature request related to a problem?

Hello Roku had the private listening. Can you add that and send sound over devices connected to HA?

### Feature Request

Hello Roku had the private listening. Can you add that and send sound over devices connected to HA?

**Comment by PRProd** [comment]
Greetings @Nash738850!

Thank you for submitting a great idea to help make the Firemote card even better! Unfortunately, the quick answer to your question is no.  This is not something that I have the ability to do.  If you are interested in understanding why, please read further.

The most important thing to understand is the difference between an [integration](https://www.home-assistant.io/getting-started/concepts-terminology/#integrations) and a dashboard [card](https://www.home-assistant.io/dashboards/cards/).
 - **Integrations**: Integrations connect and integrate Home Assistant with devices, services, and more. They contain all the logic to handle vendor- and device-specific implementations, such as authentication or specific protocols. (as defined by the [Home Assistant glossary](https://www.home-assistant.io/docs/glossary/))
 - **Cards**: Cards are used in a dashboard as a way to interact with the various integrations that are present in your Home Assistant system.  Cards can turn lights on and off, adjust a thermostat, or simply display data such as weather or statuses.

This distinction is important because it explains [how Firemote works](https://github.com/PRProd/HA-Firemote/wiki#how-does-firemote-send-commands-to-my-devices).  As an illustration:
![image](https://github.com/user-attachments/assets/74e843e0-85a9-48d1-ab2b-bde142a286fa)

As you can see in the illustration, the Firemote card does not directly communicate with your Roku device.  The Firemote card communicates with Home Assistant, and Home Assistant requires the [Roku integration](https://www.home-assistant.io/integrations/roku/) to send and receive commands from your Roku device.

Since Firemote does *not* communicate directly with your media player, its abilities are limited to the abilities of the Home Assistant [Roku integration](https://www.home-assistant.io/integrations/roku/).  If the integration cannot do it, then Firemote can't do it either.

Currently, the [Roku integration](https://www.home-assistant.io/integrations/roku/) does not include a way to do what you are asking.  Roku doesn't openly provide a way to utilize all of a device's features outside of using their own hardware.  Therefore, the [Roku integration](https://www.home-assistant.io/integrations/roku/)'s author @ctalkington is limited to what Roku allows, which actually is quite a bit!  [(click here to see Roku's documentation)](https://developer.roku.com/docs/developer-program/dev-tools/external-control-api.md)  If you were to open a [feature request](https://community.home-assistant.io/c/feature-requests/13) or a [new issue](https://github.com/home-assistant/core/issues/new/choose) to ask for this to be added, it will be rejected if that functionality is not available directly from Roku.  You'll need to review [Roku's documentation](https://developer.roku.com/docs/developer-program/dev-tools/external-control-api.md) for yourself to find out if private listening is even an option outside of using their hardware or closed source applications.

I'm sorry that I couldn't help you with this, but I hope that my explanation was helpful.

-Doug
