### ISSUE TITLE
The "Home" button no longer lights up

### ISSUE THREAD

**Issue by Jonny-T-cyber** [PRProd/HA-Firemote#524]
### Describe the bug

By clicking on the "Home" button the TV displays the home screen correctly but the button on the remote control no longer lights up as it did before.

### To Reproduce

Click on the "Home" button

### Expected Behavior

The "home" button on the remote should light up, as does the "power" button:

![image](https://github.com/user-attachments/assets/7af1a647-e073-4ba8-916c-7c61c0f94a7d)

Note that it lights up when setting other versions but not with the "Fire TV Stick 4K Max 2nd Gen (2023)".

### Which Type of Device Do You Own?

Fire TV Stick 4K Max 2nd Gen (2023)

**Comment by PRProd** [comment]
Hello again @Jonny-T-cyber!

The [Fire TV Stick 4K Max 2nd Gen 2023](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-Max-2nd-Gen-(2023)) is an interesting and somewhat frustrating model.  The same is true of the [Fire TV Stick 4K 2nd Gen 2023](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-2nd-Gen-(2023)).  

Neither of these devices allow the Home Assistant [Android Debug Bridge](https://www.home-assistant.io/integrations/androidtv) integration to see which app is active.  Because of that limitation, when using one of those devices through Firemote it is not possible to light up the active app button, or the Home button as you reported.

> Note that it lights up when setting other versions but not with the "Fire TV Stick 4K Max 2nd Gen (2023)".

This is an interesting comment.  If you are switching to a different **Amazon Fire Device Model** in the Firemote UI and the *you are* seeing the proper items light up, then you do not actually own a [Fire TV Stick 4K Max 2nd Gen 2023](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-Max-2nd-Gen-(2023)).

To find out what model you own, try this:

From the home screen, click the Gear icon and then select **My Fire TV**
![image](https://github.com/user-attachments/assets/3ec0058e-c182-4435-b974-1d6033621d8e)

Next, click on **About**
![image](https://github.com/user-attachments/assets/91ae0cd3-708b-48e5-8a10-c01eaf227ca0)

On the next screen, it will show your **Device Type**.  This is what my Fire TV Cube (3rd Gen) shows me in that menu
![image](https://github.com/user-attachments/assets/8f1a41c2-a66e-4718-8596-22fe4891c088)


After finding out the correct model of your Fire TV Stick, you'll want to choose that model from the Firemote UI
![image](https://github.com/user-attachments/assets/bc4be910-61cc-49f4-9ed0-d26ea7b14bd7)


I hope this helps!

-Doug
