### ISSUE TITLE
[New App Shortcut]: TELUS TV+

### ISSUE THREAD

**Issue by asc722** [PRProd/HA-Firemote#531]
### App Name

Telus TV+

### Device Platform

NVIDIA Shield

### Required Information

adb_response: mSurface=Surface(name=com.telus.mediaroom.tvx.byod/tv.threess.threeready.ui.generic.activity.MainActivity)/@0x781e9a3
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0x4aa2ece
  mInputMethodTarget in display# 0 Window{b06f0c7 u0 com.telus.mediaroom.tvx.byod/tv.threess.threeready.ui.generic.activity.MainActivity}

**Comment by PRProd** [comment]
Greetings @asc722!

I have just published Firemote version [v4.1.1](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.1) which contains your app shortcut request.  Since I am unable to download and test this launch for myself in my region, please let me know if you have any difficulties when trying to use it.

Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by asc722** [comment]
Thanks!!!!
