### ISSUE TITLE
Keyboard entry in Prime Video app doesn't seem to work on Android/Google TV

### ISSUE THREAD

**Issue by skavan** [PRProd/HA-Firemote#533]
### Describe the bug

I can't get the keyboard input to work inside the prime video app. 
1. Regular keyboard input doesn't send the keystrokes, tested on computer, tablet and phone. works fine on Netflix, Home Screen etc..
2. When I launch the keyboard from my phone, there is an additional mini thing, as my phone homeassistant is connected via nabu casa so I can access homeassistant remotely. This triggers a weird message in the dialog:
`The page at https://jkgcfeljfglerglfgkl....ui.nabu...` vs the normal (local) message of `homeassistant.local:8123 says'.
It still works in this case in Netflix, Home page etc... it's just cosmetic. 

### To Reproduce

On Google TV, go to any Prime Video app. Click search button, hit keyboard button on firemote...enter some text and click OK. Nothing happens. Probably a Prime Video app issue.

### Expected Behavior

It should just work!

### Which Type of Device Do You Own?

S24 Ultra, A9+ Tablet, Multiple PC based browsers.

**Comment by skavan** [comment]
Some investigation at my end...and "hope"...
1. It seems there are several different search mechanisms supported by google tv:

```
adb shell input keyevent 84
adb shell input keyevent 117
adb shell input keyevent 118
adb shell input keyevent 219
adb shell input keyevent 231
```

If I use 117 from developer tools, while in Prime it jumps to a search window, saying "use the keyboard on your mobile device".
Then the firemote keyboard works -- but one issue remains. It doesn't send a terminating 'enter' and there is no way to confirm the search using any on screen option. For this to work, we need an enter or done button on your keyboard entry dialog. or a checkbox (that remembers its default). 

I tried sending adb commands to tell the search box I'm done...but to no avail!

**Comment by skavan** [comment]
Forgot to mention, if we could get the terminating 'enter' then I could create a search button, that fired 117 from anywhere!

**Comment by PRProd** [comment]
I have other obligations at this very moment, but if you're still actively looking for adb commands to help you, perhaps one of these links might be helpful to find the "enter"?

 - https://github.com/PRProd/HA-Firemote/wiki/onn.-Google-TV-4K-Streaming-Box-(2023)
 - https://github.com/PRProd/HA-Firemote/wiki/Smart-TV---Fire-TV-4-Series-(2021)
 - https://github.com/PRProd/HA-Firemote/wiki/Homatics-Box-R-4K-Plus
 
(scroll down on any of these links for charts)

 There's a lot of overlap between different Android devices.  I'm not sure which device type you own.

**Comment by skavan** [comment]
FYI - I'm still experimenting with the key codes...but none of them simulate or are recognized as an OK button! It's Google TV inside a Hisense UST Projector. Seems like stock Google TV.

**Comment by PRProd** [comment]
@skavan ~  Life has been busy.  I'm just not starting to look at this.  I'll let you know what I can come up with

**Comment by PRProd** [comment]
I think I found the answer to your "enter" problem, but the unfortunate news is that the search window that pops up is simply a "google search", so it won't exclusively look through Prime.  This is what I did but your situation might be completely different:
<br>
Run this first to bring up the "Choose input method" menu, and select Gboard:
``adb shell input keyevent 63``

![image](https://github.com/user-attachments/assets/04b0fc6d-4c59-463c-9544-c5ebfb3625fd)

Now run the search command that you've been using:
``adb shell input keyevent 117``

![image](https://github.com/user-attachments/assets/e877fd0f-9295-44df-8198-44fd808617b4)

Then use the Firemote keyboard as usual:
![image](https://github.com/user-attachments/assets/671abdfb-7715-4d83-8dd6-15aca0c63315)
![image](https://github.com/user-attachments/assets/07d90f8b-d018-489f-8de7-bd2746f615e4)

At this point you can use this command to submit your search term:
``adb shell input keyevent 66``

BUT... the result is unexpected
![image](https://github.com/user-attachments/assets/eda6d8b9-30d9-4807-a972-e5c2d7b24abe)
<br>
<br>

The key difference for me between if ``adb shell input keyevent 66`` worked or not was the keyboard I chose with the first step ``adb shell input keyevent 63``

Unfortunately, I don't think this solves the issue you were asking about from the beginning.  But, since your system is different from mine, please try these steps and let me know if anything exciting happens on your end.  

Sorry for the delayed response.

-Doug

**Comment by PRProd** [comment]
@skavan ~

Since your issue specifically mentions the keyboard not working in the Prime Video app, I adjusted the title of this issue to reflect that.

Also, unfortunately since this is a limitation of how the latest version of the Prime video app behaves, I do not know if there will be a way around this.  Your solution, plus maybe the stuff I suggested could be the best way around the situation, so I'm anxious to hear if what I posted above is helpful.

-Doug
