### ISSUE TITLE
[New App Shortcut]: ICI Tou.tv (Chromecast)

### ISSUE THREAD

**Issue by gemond** [PRProd/HA-Firemote#534]
### App Name

ICI Tou.tv

### Device Platform

Chromecast

### App Store Link and/or URL to .apk file if sideloaded

https://play.google.com/store/apps/details?id=tv.tou.android&hl=fr_CA

### Required Information

adb_response: mSurface=Surface(name=tv.toutv.androidtv/tv.tou.android.home.views.activities.MainActivityTv)/@0xdaf3ed7
      mSurface=Surface(name=com.android.systemui.ImageWallpaper)/@0xa3ef173

### Optional Comments

Using the following ADB command starts the application:
adb shell am start -n tv.toutv.androidtv/tv.tou.android.home.views.activities.MainActivityTv

**Comment by PRProd** [comment]
Greetings @gemond!

I have just published Firemote version [v4.1.1](https://github.com/PRProd/HA-Firemote/releases/tag/v4.1.1) which contains your app shortcut request.  Since I am unable to download and test this launch for myself in my region, please let me know if you have any difficulties when trying to use it.

Enjoy!

-Doug
<hr>

After updating to the newest version, if you are unable to see the new updates on your Firemote card, visit [this link](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh) for help.

**Comment by gemond** [comment]
Working great, thank you!
