### ISSUE TITLE
[New App Shortcut]: Magenta TV Deutschland

### ISSUE THREAD

**Issue by benedikt-wue** [PRProd/HA-Firemote#563]
### App Name

Magenta TV Deutschland

### Device Platform

Chromecast

### Required Information

Can't get it work ony Phillips TV

**Comment by PRProd** [comment]
Greetings @benedikt-wue!

My apologies, I'm confused by your responses that do not seem to match each-other:

> ### Device Platform
> Chromecast

> ### Required Information
> Can't get it work ony Phillips TV


Can you help me identify what type of [supported media player](https://github.com/PRProd/HA-Firemote?tab=readme-ov-file#prerequisites) you own?

-Doug

**Comment by PRProd** [comment]
@benedikt-wue ~ Have you had a chance to look into this yet?

**Comment by benedikt-wue** [comment]
I have a Philips TV with built-in Android TV v11 and a built-in Chromecast... Maybe you have a solution for me?

**Comment by PRProd** [comment]
@benedikt-wue ~

I can try to help you with this, but since your Phillips Android OS TV is not yet an officially [supported device](https://github.com/PRProd/HA-Firemote/wiki/Supported-Devices), I likely will not be adding this request the Firemote project unless this app also works across other supported devices.

If you are interested in having Phillips Android TV officially added to the Firemote project, please [vote for it here](https://github.com/PRProd/HA-Firemote/discussions/41).  Community input like yours has been a major factor in deciding on the direction of the Firemote project.

Please help me understand more about the Magenta TV Deutschland app by following [the instructions listed here](https://github.com/PRProd/HA-Firemote/wiki/Providing-Details-for-App-Launcher-Requests#for-fire-tv-chromecast-nvidia-shield-xiaomi-mi-and-other-android-based-devices) and replying with the results.  If English isn't your native language, you can also find the same instructions in [this video tutorial](https://youtu.be/XMBs51zkD7k) with proper captions that YouTube can auto translate into your preferred language.

I look forward to hearing back from you soon.

-Doug

**Comment by galmi77** [comment]
Didn't know how to fill out all the required informations, so I added a new Issue:
https://github.com/PRProd/HA-Firemote/issues/581

**Comment by PRProd** [comment]
Closing this in favor of the new issue #581
