### ISSUE TITLE
[Feature Request]: Add Support for SkyQ Remote

### ISSUE THREAD

**Issue by bluenazgul** [PRProd/HA-Firemote#579]
### Is your feature request related to a problem?

Feature Request

### Feature Request

Since HA 2024.12 we have finally official support for the [Sky Q Remote](https://www.home-assistant.io/integrations/sky_remote/), would it be possible to extend your "HA-Firemote" for the Sky Q Remote too?

**Comment by PRProd** [comment]
Greetings @bluenazgul!

Thank you for your request!  As Firemote's popularity has been growing, I've received many requests similar to yours to add new device families.  Because of the overwhelming number of requests, I've been hosting a [poll](https://github.com/PRProd/HA-Firemote/discussions/41) where Firemote users can vote to guide the direction of the Firemote project.

Please visit [Poll: Vote for what gets added next! #41](https://github.com/PRProd/HA-Firemote/discussions/41) and cast your vote there.  Good luck!

-Doug
