### ISSUE TITLE
[Feature Request]: Control for UK Virgin Media TV 360

### ISSUE THREAD

**Issue by woody166** [PRProd/HA-Firemote#588]
### Is your feature request related to a problem?

N/A

### Feature Request

Is it possible to extend your device support for Virgin Media 360TV box, currently supported by the LG Horizon HACS app

**Comment by PRProd** [comment]
Greetings @woody166!

Thank you for your request! As Firemote's popularity has been growing, I've received many requests similar to yours to add new device families. Because of the overwhelming number of requests, I've been hosting a [poll](https://github.com/PRProd/HA-Firemote/discussions/41) where Firemote users can vote to guide the direction of the Firemote project.

Please visit https://github.com/PRProd/HA-Firemote/discussions/41 and cast your vote there. Good luck!

-Doug
