### ISSUE TITLE
[New App Shortcut]: UniFi Protect

### ISSUE THREAD

**Issue by rgabel56** [PRProd/HA-Firemote#596]
### App Name

UniFi Protect

### Device Platform

Apple TV

### App Store Link and/or URL to .apk file if sideloaded

https://apps.apple.com/us/app/unifi-protect/id1392492235

### Required Information

source_list: Protect

**Comment by PRProd** [comment]
Greetings @rgabel56!

You're in luck!  **Unifi Protect** was requested in [issue #286](https://github.com/PRProd/HA-Firemote/issues/286) and around 11 months ago, Firemote version [v3.2.0](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0) was released and the Apple TV launcher for Unifi Protect was included.

![image](https://github.com/user-attachments/assets/eec60060-c1b3-426b-bc23-ff5e16bc57e2)
![image](https://github.com/user-attachments/assets/9ff7ab6a-fda9-4c8c-83ca-1425759addfa)

If you haven't updated your Firemote version since Jan 23 2024, I recommend downloading the [latest version](https://github.com/PRProd/HA-Firemote/releases/latest) where you will find [over 335 app launchers](https://github.com/PRProd/HA-Firemote/wiki/Firemote-App-Launchers) to choose from!

I hope this helps!  Please let me know if you need any further assistance.

-Doug

**Comment by rgabel56** [comment]
Sorry... I only checked for 'Protect' and not 'Unifi Protect' in the App list.
