### ISSUE TITLE
Feature request: change card size

### ISSUE THREAD

**Issue by jscherry** [PRProd/HA-Firemote#7]
Is there a way to make the remote smaller? Love the remote so far, thanks.

**Comment by PRProd** [comment]
Hello @jscherry 👋 
I'm glad to hear that you love the card so far!  Thanks for your suggestion!

I hesitate to make the default size any smaller because when tap targets (remote buttons) are smaller and therefore closer together, the risk of hitting a wrong button, or even missing a button will grow.  I hate it when I "fat finger" a physical remote and accidentally do the exact opposite of what I wanted.  😀  Maybe that's just me?

I'm going to take some time and explore how resizing changes the usability, good or bad, and I'll share the results.  Thanks for the suggestion!

**Comment by toddsay** [comment]
For my use (from a laptop web page) it could be a little smaller, but thinking from a touch screen perspective the buttons seem about right, so it probably shouldn't be reduced by much.

The thing that's unusual about this card is that it is so "tall and thin", taking up only half the available width in many dashboard scenarios. It feels like wasted space, so I prefer to put it within a `horizontal-stack` card to share that width with something else. Currently I'm pairing it with a `spotify-card`, showing my list of playlists next to the remote (not directly related, but at least they're both "media").

**Comment by PRProd** [comment]
### [Version 1.7.0](https://github.com/PRProd/HA-Firemote/releases/tag/v1.7.0) is now available!

Scaling is here!  Adjust the card size as small or as large as you'd like!  @jscherry & @toddsay, please let me know if this is what you were hoping for.   Thanks for the input!

**Comment by jscherry** [comment]
Thanks so much!

**Comment by toddsay** [comment]
Works nicely, thanks!
