### ISSUE TITLE
[New App Shortcuts]: Crunchyroll & Oqee for all platforms

### ISSUE THREAD

**Issue by Martof** [PRProd/HA-Firemote#71]
### App Name

Oquee

### Device Platform

Freebox Player Pop (Android TV)

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

Hello

I use Xiaomi as device Family and Mi Box S as device Type.
I use the model APp Launcher 2.
Do you think it is possible to add Oquee on this device?
Thanks in advance

**Comment by Martof** [comment]
Also, on the same plateform, I would like to have Crunchyroll if it is possible.

**Comment by PRProd** [comment]
Hello @Martof!  Your requests have been added to the latest release [v2.1.6](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.6)

Also, please include your voice over at #41 if you'd like to see official support for other device types, such as your Freebox Player Pop (Android TV)

**Comment by PRProd** [comment]
(accidentally cross-posted in #72 - my fault, not yours)
> Thanks a lot Doug.
Crunchy roll works perfectly.
It seems that Oqee doesn't work.
For information on my player the app name is oqee.launcher. I don't know if
the difference is important.

Absolutely @Martof!  The difference you noted is the reason why it's not working on your Freebox Player Pop (Android TV) device.  Even though your device isn't officially supported by Firemote yet, I'll see what I can do... for a star?  :grinning: 

Could you kindly follow the steps under [Details For App Requests](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) and post the results into this thread?  That level of detail is extremely important to see since I do not own the kind of device you have.

**Comment by PRProd** [comment]
@Martof - Have you had a chance to look at this yet?  Please let me know if you have any difficulty when trying to follow the steps.  Thanks.

**Comment by Martof** [comment]
Dear Doug, I give you a star. I'll try to do the steps soon

**Comment by PRProd** [comment]
@Martof - Any luck here?

**Comment by PRProd** [comment]
Closing this issue for now since I haven't heard back.  Feel free to re-open it if you wish for me to continue working on it.
