### ISSUE TITLE
Magenta TV Button not working

### ISSUE THREAD

**Issue by dropdennisdead** [PRProd/HA-Firemote#81]
### Describe the bug

Hi! :)

i installed your addon over HACS and noticed, all App buttons are working except the 'MagentaTV' button. 
It has no function.

Through the FireTV integration in Homeassistant I saw that the Magenta TV source is recognized as "tv.accedo.xdk.dtag.production", not "MagentaTV".
Is there a solution to the problem or any suggestions what I could test?

Thanks in advance!

Dennis

### To Reproduce

1

### Expected Behavior

Please Help

### Which Type of Device Do You Own?

Fire TV Cube, Synology NAS, Mac Mini

**Comment by PRProd** [comment]
Dennis,

Thanks for reaching out!  I think I know what the issue is.  In issue #58 I originally created the Magenta TV app button for an Android TV device that is not a Fire TV Cube (or not in the Amazon fire tv family).  I have found that the base app names sometimes are different between the Fire TV family, and other Android TV devices, and I believe that this is the case here too.

I've just released [Version 2.1.8](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.8) for download which I expect will fix the issue for you.  Please let me know your results.

**Comment by PRProd** [comment]
Bummer... sorry about that.  I'm going to need some more information from you.

Please follow the steps listed [here](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) under [Details For App Requests](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) and post your results.  That should give me enough information to try again.

Thanks for your patience.  Magenta TV is an app that is unavailable in my region (US) so I unfortunately cannot do any testing.  I appreciate your help.

**Comment by dropdennisdead** [comment]
source_list: tv.accedo.xdk.dtag.production
app_id: tv.accedo.xdk.dtag.production
source: tv.accedo.xdk.dtag.production
adb_response: mSurface=Surface(name=tv.accedo.xdk.dtag.production/tv.accedo.xdk.dtag.MainActivity)/@0xee57adf
  mCurrentFocus=Window{708e48c u0 tv.accedo.xdk.dtag.production/tv.accedo.xdk.dtag.MainActivity}
  mFocusedApp=AppWindowToken{4644a73 token=Token{f7b96e2 ActivityRecord{10da3ad u0 tv.accedo.xdk.dtag.production/tv.accedo.xdk.dtag.MainActivity t2895}}}

**Comment by PRProd** [comment]
Thank you!  That's very helpful!

Before I push another release I want to be 100% sure to get it right, so will you please do one more test step for me?

I'll need you to follow most of the same steps (use only steps 2-7) as you did in the [details for app requests](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests), but with two changes:
1. Start at the Home screen of your FireTV Cube, DO NOT have the Magenta TV App open
2. Instead of the command listed in step 6, please use this instead:
```
adb shell am start -n tv.accedo.xdk.dtag.production/tv.accedo.xdk.dtag.MainActivity
```
![image](https://user-images.githubusercontent.com/25486599/235240118-3cb5c8c7-7fcb-41fa-b3ec-9e8d27270033.png)

After pressing the Call Service button, the expected behavior is that your Fire Cube will switch to the Magenta TV app.  Please let me know if this happens.

**Comment by dropdennisdead** [comment]
it works! 
The MagentaTV App opens instantly 👍

**Comment by PRProd** [comment]
Excellent!

[Version 2.1.9](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.9) is ready for download now.  This should work for you!

**Comment by dropdennisdead** [comment]
Thanks a lot man! 😃👍

**Comment by PRProd** [comment]
You're very welcome!
