### ISSUE TITLE
[New App Shortcut]: Kayo

### ISSUE THREAD

**Issue by phatrickk** [PRProd/HA-Firemote#86]
### App Name

Kayo

### Device Platform

NVIDIA Shield

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

Australian streaming service

**Comment by phatrickk** [comment]
https://play.google.com/store/apps/details?id=au.com.kayosports

**Comment by PRProd** [comment]
@phatrickk - can you confirm the app name for me by following the instructions [here](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F) under [Details For App Requests](https://github.com/PRProd/HA-Firemote/wiki/How-Can-I-Help%3F#details-for-app-requests) -  I'm having a little trouble finding an Android TV APK to download (since it's not available in my country via the play store) with the name au.com.kayosports that isn't meant for a mobile device.

**Comment by PRProd** [comment]
@phatrickk - I made an educated guess on the app launch command, so I really need your input.  Please download the latest pre-release, [Version 2.1.10-beta1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.10-beta1) of HA-Firemote and check if the "Kayo" app launch button is functioning as expected.  If not, please follow the previous instructions so I can see the additional data that I need.  Thanks!

**Comment by phatrickk** [comment]
> @phatrickk - I made an educated guess on the app launch command, so I really need your input. Please download the latest pre-release, [Version 2.1.10-beta1](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.10-beta1) of HA-Firemote and check if the "Kayo" app launch button is functioning as expected. If not, please follow the previous instructions so I can see the additional data that I need. Thanks!

Confirmed that this is working, thanks.

**Comment by PRProd** [comment]
Thanks for the confirmation!  

[Version 2.1.10](https://github.com/PRProd/HA-Firemote/releases/tag/v2.1.10) is now available which officially supports your app shortcut request.  Thanks for contributing!
